---
title: "PPFE_Figure_1_Barplots"
author: "Jannik Ruwisch"
date: "2025-03-09"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.width = 14,
                      fig.height = 7,
                      #dpi = 1200,
                      dev = "png",
                      cache = F,
                      fig.path= "C:/Users/Jannik/OneDrive/PNE_MHH/AG_Prasse_OneDrive/PPFE/PPFE_Nuc_Seq/Batch_integration/ppfe_epithelium/")
```

```{r}
library(SCP)
library(Seurat)
library(SeuratObject)
#library(renv)
#library(SCP)
library(dplyr)
library(tidyverse)
library(tidyseurat)
library(ggpubr)

folder <- choose.dir()
```

```{r}
test <- readRDS("PPFE_cleaned_datasetes_ALL_RPCA_clean_integrated_22_12_2024.rds")
```


```{r}
# Color Palettes"
dis_pal <- palette_scp(x = test$disease.ident, palcolor = c("royalblue", "red3", "#ffd59b"))
cohort_pal_heat <- palette_scp(x = test$Cohort, palcolor = c("grey88", "grey58", "grey18"))
cohort_pal <-  c("royalblue", "red1", "darkred", "#ffd59b")
lin_pal <- palette_scp(x = test$Lineage,palcolor = c( "#cc79a7", "#009e73", "#5654e9", "#d55e00"  , "#e69f00"))
subject_pal <-  palette_scp(palette = "Set1", n = length(test$orig.ident %>% unique()), matched = F)
```

```{r}
folder <- choose.dir()
```


```{r}
# Start from here...
test <- test %>%
  mutate(Cohort = case_when(orig.ident_final == "PPFE040" ~ "Germany",
                            .default = Cohort))


test <- test %>%
  mutate(orig.ident = case_when(Project == "PPFE" ~ orig.ident,
                                  Project == "IPF" ~ substr(orig.ident, start = 1, stop = 10))
  )

#test$disCohort_FINAL %>% unique()

test$disCohort_FINAL <- paste0(test$Cohort, "_", test$disease.ident)
```



```{r}
# Adjust for patient idents based on encryptiont table 
test <- test%>%
  mutate(orig.ident_final = case_when(orig.ident == "CTRL_GLE822" ~ "CTR008",
                                      orig.ident == "CTRL_GLE891" ~ "CTR011",
                                      orig.ident == "CTRL_CTRL002" ~ "CTR002",
                                      orig.ident == "CTRL_GLR632" ~ "CTR072",
                                      orig.ident == "CTRL_GLR635" ~ "CTR073",
                                      orig.ident == "CTRL_CTRL007" ~ "CTR007",
                                      orig.ident == "CTRL_GLE639" ~ "CTR075",
                                      orig.ident == "CTRL_GLR609" ~ "CTR031",
                                      orig.ident == "CTRL_GLR725" ~ "CTR064",
                                      orig.ident == "CTRL_CTR048" ~ "CTR048",
                                      orig.ident == "CTRL_CTR068" ~ "CTR068",
                                      orig.ident == "CTRL_CTR051" ~ "CTR051",
                                      orig.ident == "CTRL_CTR071" ~ "CTR071",
                                      orig.ident == "CTRL_CTR058" ~ "CTR058",
                                      orig.ident == "CTRL_CTR069" ~ "CTR069",
                                      orig.ident == "CTRL_CTR070" ~ "CTR070",
                                      orig.ident == "PPFE_PPFE015a" ~ "PPFE015",
                                      orig.ident == "PPFE_PPFE015b" ~ "PPFE015",
                                      orig.ident == "PPFE_PPFE005" ~ "PPFE002",
                                      orig.ident == "PPFE_PPFE42" ~ "PPFE006",
                                      
                                      orig.ident == "PPFE_PPFE001" ~ "PPFE001",
                                      orig.ident == "PPFE_PPFE002" ~ "PPFE002",
                                      orig.ident == "PPFE_PPFE003" ~ "PPFE003",
                                      orig.ident == "PPFE_PPFE004" ~ "PPFE004",
                                      orig.ident == "PPFE_PPFE005" ~ "PPFE005",
                                      orig.ident == "PPFE_PPFE006" ~ "PPFE006",
                                      orig.ident == "PPFE_PPFE007" ~ "PPFE007",
                                      orig.ident == "PPFE_PPFE008" ~ "PPFE008",
                                      orig.ident == "PPFE_PPFE009" ~ "PPFE009",
                                      orig.ident == "PPFE_PPFE010" ~ "PPFE010",
                                      orig.ident == "PPFE_PPFE011" ~ "PPFE011",
                                      orig.ident == "PPFE_PPFE012" ~ "PPFE012",
                                      orig.ident == "PPFE_PPFE013" ~ "PPFE013",
                                      orig.ident == "PPFE_PPFE014" ~ "PPFE014",
                                      orig.ident == "PPFE_PPFE016" ~ "PPFE016",
                                      orig.ident == "PPFE_PPFE017" ~ "PPFE017",
                                      orig.ident == "PPFE_PPFE018" ~ "PPFE018",
                                      orig.ident == "PPFE_PPFE019" ~ "PPFE019",
                                      orig.ident == "PPFE_PPFE020" ~ "PPFE020",
                                      orig.ident == "PPFE_PPFE21" ~ "PPFE021",
                                      orig.ident == "PPFE_PPFE22" ~ "PPFE022",
                                      orig.ident == "PPFE_PPFE23" ~ "PPFE023",
                                      orig.ident == "PPFE_PPFE24" ~ "PPFE024",
                                      orig.ident == "PPFE_PPFE25" ~ "PPFE025",
                                      orig.ident == "PPFE_PPFE26" ~ "PPFE026",
                                      orig.ident == "PPFE_PPFE27" ~ "PPFE027",
                                      orig.ident == "PPFE_PPFE28" ~ "PPFE028",
                                      orig.ident == "PPFE_PPFE29" ~ "PPFE029",
                                      orig.ident == "PPFE_PPFE30" ~ "PPFE030",
                                      orig.ident == "PPFE_PPFE31" ~ "PPFE031",
                                      orig.ident == "PPFE_PPFE32" ~ "PPFE032",
                                      orig.ident == "PPFE_PPFE33" ~ "PPFE033",
                                      orig.ident == "PPFE_PPFE34" ~ "PPFE034",
                                      orig.ident == "PPFE_PPFE35" ~ "PPFE035",
                                      orig.ident == "PPFE_PPFE36" ~ "PPFE036",
                                      orig.ident == "PPFE_PPFE37" ~ "PPFE037",
                                      orig.ident == "PPFE_PPFE38" ~ "PPFE038",
                                      orig.ident == "PPFE_PPFE39" ~ "PPFE039",
                                      orig.ident == "PPFE_PPFE40" ~ "PPFE040",
                                      orig.ident == "PPFE_PPFE41" ~ "PPFE041",
                                      orig.ident == "PPFE_PPFE43" ~ "PPFE043",
                                      orig.ident == "PPFE_PPFE44" ~ "PPFE044",
                                      .default = orig.ident)
         )

test$orig.ident_final %>% unique()

test$orig.ident_old <- test$orig.ident
test$orig.ident <- test$orig.ident_final

```

## Color Palette Settings
```{r}
pal_cluster_scp_pal <- c(
  # Epithelial Cells
  "#7F3C8D",  # AEC2
  "#199784",  # AEC1
  "#715588",  # Club
  "#8B8B60",  # AEC_intermediate
  "#A5AA99",  # Basal
  "#CC831E",  # Secretory
  "#E1244D",  # Aberrant_Basaloid
  "#446293",  # Goblet
  "#8BAC5C",  # Ciliated
  "#FDBF6F",  # PNEC
  "#FDBF6F",  # Mesothelium
  "#000000",  # Schwann_Neu (Not specified, placeholder)

  # Fibroblasts & Stromal Cells
  "#33A02C",  # Pericytes
  "#A6CEE3",  # Alveolar_Fb
  "#6A3D9A",  # Adventitial_Fb
  "#FB9A99",  # Subpleural_Fb
  "#CAB2D6",  # Adventitial_like_Fb
  "#B2DF8A",  # Smooth_Muscle
  "#E31A1C",  # CTHRC1_MyoFb
  "#1F78B4",  # Airway_Fb

  # Endothelial Cells
  "#4DBBD5",  # EC_pulmonary_venous
  "#F39B7F",  # EC_arterial
  "#3C5488",  # EC_general_cap
  "#E64B35",  # EC_systemic_venous
  "#8491B4",  # EC_aerocyte
  "#00A087",  # EC_lymphatic

  # Myeloid Cells
  "#C19D94",  # Fibrotic_Macrophage
  "#BE777C",  # Monocyte_derived_Macrophage
  "#FF6F00",  # Alveolar_Macrophage
  "#BA7769",  # Monocyte_nonClassical
  "#6A7998",  # Monocyte_Classical
  "#1D5152",  # DC2
  "#94CABB",  # DC1
  "#CB1700",  # Mast
  "#B7BBC9",  # IFNresp_Monocyte_derived_Macrophage
  "#58644F",  # pDC
  "#3F4041",  # Langerhans-Cells
  "#67549A",  # Macrophage_Cycling
  "#217885",  # Neutro

  # Lymphoid Cells
  "#E6F5B7",  # CD4+_TC_naive
  "#D9D7C9",  # CD4+_TC_effector_memory
  "#D9B382",  # CD4+_TC_TH1 (Not explicitly named, assumed TH1 effector memory)
  "#8DD3C7",  # Treg
  "#DED7DA",  # NK_Cells_CD16+
  "#C7D98C",  # CD8+_TC_resident_memory
  "#FFED6F",  # B_Cells_memory
  "#D8C965",  # CD8+_TC_effector_memory
  "#88ADCC",  # ILC3
  "#F9CDE4",  # gamma_delta_TC
  "#D9B382",  # CD4+_TC_TH17 (Assumed from similar CD4 TC subsets)
  "#D9B382",  # CD4+_TC_Cytotoxic (Not explicitly defined, assumed)
  "#D6EBB2",  # B_Cells_naive
  "#C2ADC0",  # Plasma_Cells
  "#C69FC7" )  # NK_Cells_CD16-
  

  lin_pal <- palette_scp(x = test$Lineage,palcolor = c( "#cc79a7", "#009e73", "#5654e9", "#d55e00"  , "#e69f00"))
pal_cluster_scp_pal

pal_dis_pal <- palette_scp(x = test$disease.ident%>% unique(), palcolor = c("royalblue", "red3", "#ffd59b"), matched = F)
pal_dis_pal

pal_cohort_pal_heat <- palette_scp(x = c("Germany", "France",  "Belgium"), palcolor = c("grey88", "grey58", "grey18"), matched = F)
pal_cohort_pal_heat

pal_cohort_pal <-  c("royalblue", "red1", "darkred", "#ffd59b")
#lin_pal <- palette_scp(x = PPFE_endo$Lineage,palcolor = c( "#cc79a7", "#009e73", "#5654e9", "#d55e00"  , "#e69f00"))
pal_subject_pal <-  palette_scp(palette = "igv", x = test$orig.ident_final %>% unique(), matched = F) 
pal_subject_pal

```


# 1. Plot the Cellfrequencies
```{r}
Batch2_Fren_IDs
```

### Overall Dataset
```{r, fig.width=14, fig.height=7}
# Proportion / cell number composition per cluster
ggData = data.frame(prop.table(table(test$Lineage, test$orig.ident_final), margin = 2))
colnames(ggData) = c("Celltype_ID", "Orig.Ident",  "value")

ggData <- ggData %>%
 mutate(Disease = substr(Orig.Ident, 1,4))

subset(test, disCohort_FINAL == "France_PPFE")$orig.ident_final %>% unique()-> Batch2_Fren_IDs 
subset(test, disCohort_FINAL == "Germany_PPFE")$orig.ident_final %>% unique()-> BAtch1_Han_IDs 

BAtch1_Han_IDs <- c(BAtch1_Han_IDs, "PPFE040") # correction !! 
Batch2_Fren_IDs <- c("PPFE021", "PPFE022", "PPFE025", "PPFE026", "PPFE028", "PPFE029", 
                 "PPFE031", "PPFE032", "PPFE033", "PPFE034", "PPFE035", "PPFE037", 
                 "PPFE038",  "PPFE023", "PPFE024", "PPFE036", "PPFE039")#"PPFE040",) correction ! is German !!
subset(test, disCohort_FINAL == "Germany_CTRL")$orig.ident_final %>% unique()-> CTRL_ids
```


```{r, fig.width=14, fig.height=7}
ggData <- ggData %>%
 mutate(Disease = case_when(Orig.Ident %in% Batch2_Fren_IDs ~ "France_PPFE",
                            Orig.Ident %in% BAtch1_Han_IDs ~ "Germany_PPFE",
                            Orig.Ident %in% CTRL_ids ~ "Germany_CTRL",
                            .default = "Belgium_IPF")
        )

ggData$Disease <- factor(ggData$Disease, levels = c("Germany_CTRL", "France_PPFE", "Germany_PPFE", "Belgium_IPF"))



test$Celltype_ID_final_coarse %>% unique() -> Celltypes
levels(Celltypes)

#cluster_scp_pal <- SCP::palette_scp(x = c( "Epithelium","Mesenchyme","Endothelium", "Lymphoid","Myeloid"), palcolor = lin_pal)

patient_order <- ggData %>%
  dplyr::filter(Celltype_ID == 'Lymphoid') %>% 
  arrange(Disease, desc(value)) %>% # Zuerst nach Disease, dann nach value absteigend
  pull(Orig.Ident)

# Convert Patient_ID to a factor with the specific order
ggData$Orig.Ident <- factor(ggData$Orig.Ident, levels = patient_order)


# Calculate median values for each Celltype_ID within each Disease group
medians <- ggData %>%
  dplyr::filter(Disease =="Germany_PPFE") %>%
  group_by(Disease, Celltype_ID) %>%
  summarize(median_value = median(value)) %>%
  ungroup()

# Order Celltype_ID based on median values
ordered_celltypes <- medians %>%
  group_by(Celltype_ID) %>%
  summarize(overall_median = median(median_value)) %>%
  arrange(overall_median) %>%
  pull(Celltype_ID)
ordered_celltypes

# Update the levels of Celltype_ID in ggData
ggData$Celltype_ID <- factor(ggData$Celltype_ID, levels = c( "Epithelium","Mesenchyme","Endothelium", "Myeloid","Lymphoid")
                             )

ggData
```

## Read in the Par Quantification
```{r}
parquant <- readxl::read_xlsx("C:/Users/Jannik/OneDrive/PNE_MHH/AG_Prasse_OneDrive/PPFE/Automated_Image_Analysis/Figure_1_Quantification_of_Remodeled_Parenchyma/Alv_Remodeled_Par_Quantification_PPFE_Germany_France_FINAL_03052025.xlsx")

parquant$Orig.Ident <- parquant$ID

merged_df <- dplyr::left_join(ggData, parquant, by = "Orig.Ident")
merged_df <- merged_df %>%
  mutate(Remodeled_Alv_Ratio = ifelse(is.na(Remodeled_Alv_Ratio), 0, Remodeled_Alv_Ratio),
         Alv_Remodeled_Ratio = ifelse(is.na(Alv_Remodeled_Ratio), 0, Alv_Remodeled_Ratio),
         )

merged_df$Orig.Ident <- factor(merged_df$Orig.Ident, levels = patient_order)

```
```{r}
library(ggplot2)
library(dplyr)

# Normalize the top bars to be only 1/10 of the total height
merged_df <- merged_df %>%
  mutate(Remodeled_Alv_Scaled = Remodeled_Alv_Ratio / max(Remodeled_Alv_Ratio, na.rm = TRUE), 
         Alv_Remodeled_Scaled = Alv_Remodeled_Ratio / max(Alv_Remodeled_Ratio, na.rm = TRUE))

# Create the plot
p <- ggplot(merged_df, aes(x = Orig.Ident)) +
  
  # Main stacked bar plot (Cell Type Frequencies)
  geom_bar(aes(y = value, fill = Celltype_ID), stat = "identity", position = "fill", size = 0.5, color = "black") +

  # Add new y-scale for Remodeled data
  scale_y_continuous(
    name = "Cell Type Proportion (%)",
    sec.axis = sec_axis(~ . * max(merged_df$Remodeled_Alv_Ratio, na.rm = TRUE), name = "Remodeled Ratio (%)") # Secondary y-axis
  ) +
  
  # Secondary y-axis: Overlaying bars for Remodeled Alveoli and Alveolar Remodeling
  geom_col(aes(y = Remodeled_Alv_Scaled, fill = "Remodeled Alveoli"), alpha = 0.5, width = 0.5) +
  geom_col(aes(y = Alv_Remodeled_Scaled, fill = "Alveolar Remodeling"), alpha = 0.5, width = 0.5) +

  # Labels and themes
  labs(title = "Stacked Bar Plot with Remodeled Parenchyma",
       x = "Patient ID",
       y = "Proportion (%)") + 
  scale_fill_manual(values = c(lin_pal, "Remodeled Alveoli" = "darkviolet", "Alveolar Remodeling" = "orange")) +
  theme_scp() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.y.right = element_text(color = "darkviolet"), # Highlight secondary axis
    axis.title.y.left = element_text(color = "black") # Keep main axis
  ) +
  facet_wrap(~Disease, scales = "free_x", ncol = 4) +
  NoLegend() + RotatedAxis()

p


```

```{r}
p1 <- ggplot(merged_df, aes(x = Orig.Ident, y = value*100, fill = Celltype_ID)) +
  geom_bar(stat = "identity", position = "stack", size = 0.5, color = "black") +
  labs(x = NULL,
       y = NULL) + 
  scale_fill_discrete(lin_pal) +
  scale_color_discrete(lin_pal) +
  scale_fill_manual(values = lin_pal) +
  scale_color_manual(values = lin_pal) +
  theme_scp() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~Disease, scales = "free_x", ncol = 4) + NoLegend()+RotatedAxis()

p1



plot_data <- merged_df %>%
  select(Orig.Ident,Disease,Celltype_ID, Alv_Remodeled_Ratio, Remodeled_Alv_Ratio) %>%
  pivot_longer(cols = c(Alv_Remodeled_Ratio, Remodeled_Alv_Ratio),
               names_to = "Classification",
               values_to = "Percentage") %>%
  filter(Celltype_ID == "Epithelium")

plot_data$Orig.Ident <- factor(plot_data$Orig.Ident, levels = patient_order)

# Create stacked bar plot
p2 <- ggplot(plot_data, aes(x = Orig.Ident, y = Percentage*100, fill = Classification)) +
  geom_bar(stat = "identity") +
  labs(#title = "Stacked Bar Plot of Percent Alv and Percent Remodeled per ID",
       x = NULL,
       y = NULL,
       fill = "Classification") +
  theme_scp() +
 # RotatedAxis()+
  scale_fill_manual(values = c("lightblue", "purple"))+
  scale_color_manual(values = c("lightblue", "purple"))+
  theme_scp() +
   theme(
    axis.text.x = element_blank(), 
    axis.text.x.bottom = element_blank(),  # Remove x-axis labels
    axis.title.x = element_blank(),  # Remove x-axis title
    axis.ticks.x = element_blank()#,  # Remove x-axis ticks
    #strip.text = element_blank() 
    )+ # Remove facet titles
  facet_wrap(~Disease, scales = "free_x", ncol = 4) + NoLegend()+RotatedAxis()+
  scale_y_continuous(breaks = c(0,100))
p2
```
```{r}
pdf((file = file.path(folder,"Figure_1Stackedbarplots_lineage.pdf")), width = 17, height = 6.5)
p1
dev.off()

pdf((file = file.path(folder,"Figure_1Stackedbarplots_RemodAlv.pdf")), width = 17, height = 1.0)
p2
dev.off()
```

## Correlation Plot
```{r}
library(ggplot2)
library(dplyr)
library(ggpubr)
lineages <- merged_df$Celltype_ID %>% levels()

# Define custom colors and shapes
disease_colors <- c("Germany_PPFE" = "darkred", "France_PPFE" = "pink")
disease_shapes <- c("Germany_PPFE" = 16, "France_PPFE" = 17)  # e.g., filled circle and triangle

# Generate the plots
plot_list <- lapply(lineages, function(x){
  cor_data <- merged_df %>% 
    filter(Celltype_ID == x) %>%
    filter(Disease %in% c("Germany_PPFE", "France_PPFE")) %>%
    mutate(Frequency = value * 100,
           Remodeled_Parenchyma = Remodeled_Alv_Ratio * 100)

  ggplot(cor_data, aes(x = Frequency, y = Remodeled_Parenchyma)) +
    geom_point(aes(color = Disease, shape = Disease), size = 2) +  # color & shape for points only
    geom_smooth(method = "lm", se = TRUE, color = "black") +       # single correlation line
    stat_cor(method = "pearson") +
    scale_color_manual(values = disease_colors) +
    scale_shape_manual(values = disease_shapes) +
    labs(
      x = paste0("Frequency of ", x, " (%)"),
      y = "Remodeled Parenchyma (%)",
      title = paste0("Correlation: ", x)
    ) +
    theme_scp()
})

# Arrange and save
combined_plot <- ggarrange(plotlist = plot_list, ncol = 2, nrow = ceiling(length(plot_list)/2), common.legend = T)
ggsave("Immune_Correlation_Multipanel.pdf", combined_plot, width = 6, height = 8)

```


```{r}
cor_data <- merged_df %>% 
  filter(Celltype_ID == "Lymphoid") %>%
  filter(Disease == "Germany_PPFE" | Disease == "France_PPFE")

# Plot with correlation
cor_plot <- ggplot(cor_data, aes(x = value, y = Remodeled_Alv_Ratio)) +
  geom_point(size = 2, color = "darkred") +
  geom_smooth(method = "lm", se = TRUE, color = "black") +
  stat_cor(method = "pearson") +  # Display correlation coefficient
  labs(
    x = "Frequency of Immune Cells (%)",
    y = "Percent Remodeled Parenchyma (%)",
    title = "Correlation between Immune Cell Frequency and Remodeled Parenchyma"
  ) +
  theme_scp()

cor_plot

```

