---
title: "PPFE_Mesenchyme_DE"
author: "Jannik Ruwisch"
date: "2025-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.width = 14,
                      fig.height = 7,
                      #dpi = 1200,
                      dev = "png",
                      cache = F,
                      fig.path= "C:/Users/Jannik/OneDrive/PNE_MHH/AG_Prasse_OneDrive/PPFE/PPFE_Nuc_Seq/Batch_integration/ppfe_mesenchyme/")
```

```{r}
# INfos
## Dataset was created with 10X Flex Tech >> Lower UMIs, Features and Counts than Xenium ! 
```

```{r}
library(SCP)
library(Seurat)
library(SeuratObject)
#library(renv)
#library(SCP)
library(dplyr)
library(tidyverse)
library(tidyseurat)
library(ggpubr)
```


 # IPF Integration

### Load IPF data
```{r}
PPFE_mes <- readRDS("C:/Users/Jannik/OneDrive/PNE_MHH/AG_Prasse_OneDrive/PPFE/PPFE_Nuc_Seq/Batch_integration/ppfe_mesenchyme/PPFE_b1b2_IPF_Mes_int_RPCA_28112024.rds")

DefaultAssay(PPFE_mes) <- "RNA"

PPFE_mes <- PPFE_mes %>%
  mutate(orig.ident = case_when(Project == "PPFE" ~ orig.ident,
                                  Project == "IPF" ~ substr(orig.ident, start = 1, stop = 10))
  )
```

```{r}
PPFE_mes$orig.ident %>% unique()
```

```{r}
# Adjust for patient idents based on encryptiont table 
PPFE_mes <- PPFE_mes%>%
  mutate(orig.ident_final = case_when(orig.ident == "CTRL_GLE822" ~ "CTR008",
                                      orig.ident == "CTRL_GLE891" ~ "CTR011",
                                      orig.ident == "CTRL_CTRL002" ~ "CTR002",
                                      orig.ident == "CTRL_GLR632" ~ "CTR072",
                                      orig.ident == "CTRL_GLR635" ~ "CTR073",
                                      orig.ident == "CTRL_CTRL007" ~ "CTR007",
                                      orig.ident == "CTRL_GLE639" ~ "CTR075",
                                      orig.ident == "CTRL_GLR609" ~ "CTR031",
                                      orig.ident == "CTRL_GLR725" ~ "CTR064",
                                      orig.ident == "CTRL_CTR048" ~ "CTR048",
                                      orig.ident == "CTRL_CTR068" ~ "CTR068",
                                      orig.ident == "CTRL_CTR051" ~ "CTR051",
                                      orig.ident == "CTRL_CTR071" ~ "CTR071",
                                      orig.ident == "CTRL_CTR058" ~ "CTR058",
                                      orig.ident == "CTRL_CTR069" ~ "CTR069",
                                      orig.ident == "CTRL_CTR070" ~ "CTR070",
                                      orig.ident == "PPFE_PPFE015a" ~ "PPFE015",
                                      orig.ident == "PPFE_PPFE015b" ~ "PPFE015",
                                      orig.ident == "PPFE_PPFE005" ~ "PPFE002",
                                      orig.ident == "PPFE_PPFE42" ~ "PPFE006",
                                      
                                      orig.ident == "PPFE_PPFE001" ~ "PPFE001",
                                      orig.ident == "PPFE_PPFE002" ~ "PPFE002",
                                      orig.ident == "PPFE_PPFE003" ~ "PPFE003",
                                      orig.ident == "PPFE_PPFE004" ~ "PPFE004",
                                      orig.ident == "PPFE_PPFE005" ~ "PPFE005",
                                      orig.ident == "PPFE_PPFE006" ~ "PPFE006",
                                      orig.ident == "PPFE_PPFE007" ~ "PPFE007",
                                      orig.ident == "PPFE_PPFE008" ~ "PPFE008",
                                      orig.ident == "PPFE_PPFE009" ~ "PPFE009",
                                      orig.ident == "PPFE_PPFE010" ~ "PPFE010",
                                      orig.ident == "PPFE_PPFE011" ~ "PPFE011",
                                      orig.ident == "PPFE_PPFE012" ~ "PPFE012",
                                      orig.ident == "PPFE_PPFE013" ~ "PPFE013",
                                      orig.ident == "PPFE_PPFE014" ~ "PPFE014",
                                      orig.ident == "PPFE_PPFE016" ~ "PPFE016",
                                      orig.ident == "PPFE_PPFE017" ~ "PPFE017",
                                      orig.ident == "PPFE_PPFE018" ~ "PPFE018",
                                      orig.ident == "PPFE_PPFE019" ~ "PPFE019",
                                      orig.ident == "PPFE_PPFE020" ~ "PPFE020",
                                      orig.ident == "PPFE_PPFE21" ~ "PPFE021",
                                      orig.ident == "PPFE_PPFE22" ~ "PPFE022",
                                      orig.ident == "PPFE_PPFE23" ~ "PPFE023",
                                      orig.ident == "PPFE_PPFE24" ~ "PPFE024",
                                      orig.ident == "PPFE_PPFE25" ~ "PPFE025",
                                      orig.ident == "PPFE_PPFE26" ~ "PPFE026",
                                      orig.ident == "PPFE_PPFE27" ~ "PPFE027",
                                      orig.ident == "PPFE_PPFE28" ~ "PPFE028",
                                      orig.ident == "PPFE_PPFE29" ~ "PPFE029",
                                      orig.ident == "PPFE_PPFE30" ~ "PPFE030",
                                      orig.ident == "PPFE_PPFE31" ~ "PPFE031",
                                      orig.ident == "PPFE_PPFE32" ~ "PPFE032",
                                      orig.ident == "PPFE_PPFE33" ~ "PPFE033",
                                      orig.ident == "PPFE_PPFE34" ~ "PPFE034",
                                      orig.ident == "PPFE_PPFE35" ~ "PPFE035",
                                      orig.ident == "PPFE_PPFE36" ~ "PPFE036",
                                      orig.ident == "PPFE_PPFE37" ~ "PPFE037",
                                      orig.ident == "PPFE_PPFE38" ~ "PPFE038",
                                      orig.ident == "PPFE_PPFE39" ~ "PPFE039",
                                      orig.ident == "PPFE_PPFE40" ~ "PPFE040",
                                      orig.ident == "PPFE_PPFE41" ~ "PPFE041",
                                      orig.ident == "PPFE_PPFE43" ~ "PPFE043",
                                      orig.ident == "PPFE_PPFE44" ~ "PPFE044",
                                      .default = orig.ident)
         )

PPFE_mes$orig.ident_final %>% unique()

PPFE_mes$orig.ident_old <- PPFE_mes$orig.ident
PPFE_mes$orig.ident <- PPFE_mes$orig.ident_final

```


```{r}
test_clean <- subset(PPFE_mes, disease.ident != "IPF")

test_clean@meta.data %>% colnames()
```
```{r}
FeatureDimPlot(test_clean, features = "COL1A1", assay = "RNA", split.by = "disease.ident")

test_clean$disease.ident <- test_clean$disease.ident %>% droplevels() 
```






```{r}
CellDimPlot(test_clean, group.by = c("Celltype", "disease.ident", "orig.ident_final"), raster = F, reduction = "ReUMAPone")
```


```{r}
Degs_between_Adventitials <- FindMarkers(PPFE_mes, group.by = "Celltype_ID_coarse_heat", ident.1 = "Adventitial_Fb", ident.2 = "Adventitial_like_Fb", assay = "RNA", min.pct = 0.3,  logfc.threshold = 0.3)

# Export as dataframe 
Degs_between_Adventitials$gene <- rownames(Degs_between_Adventitials)
writexl::write_xlsx(Degs_between_Adventitials, "Degs_between_Adventitials.xlsx")

```
```{r}
PPFE_mes@tools$Integration
```


#====================

# Seurat by subject Pseudobulk
## DE Genes between Clusters
```{r}
test_clean$CelltypeID.dis <- paste(test_clean$Celltype, test_clean$disease.ident, sep = "_")
Idents(test_clean) <- "CelltypeID.dis"

#mono.de <- FindMarkers(ifnb, ident.1 = "CD14 Mono_STIM", ident.2 = "CD14 Mono_CTRL", verbose = FALSE)
#head(mono.de, n = 10)
```

```{r}
# load the inferred sample IDs of each cell
info <- test_clean@meta.data
info$BARCODE <- rownames(info)

# rename the cell IDs by substituting the '-' into '.'
info$BARCODE <- gsub(pattern = "\\-", replacement = "\\.", info$BARCODE)

# only keep the cells with high-confidence sample ID
#info <- info[grep(pattern = "SNG", x = info$BEST), ]

# remove cells with duplicated IDs in both ctrl and stim groups
info <- info[!duplicated(info$BARCODE) & !duplicated(info$BARCODE, fromLast = T), ]

# now add the sample IDs to ifnb 
rownames(info) <- info$BARCODE

#info <- info[, c("BEST"), drop = F]
#names(info) <- c("orig.ident")
test <- test_clean

test_clean <- AddMetaData(test_clean, metadata = info)

# remove cells without donor IDs
#ifnb$donor_id[is.na(ifnb$donor_id)] <- "unknown"
#ifnb <- subset(ifnb, subset = donor_id != "unknown")
```

### Aggregate Expression per Subject
```{r}
# pseudobulk the counts based on donor-condition-celltype
pseudo_ppfe <- AggregateExpression(PPFE_mes, assays = "RNA", 
                                   return.seurat = T, 
                                   group.by = c("disease.ident", "orig.ident_final", "Celltype_ID_coarse_heat"))

# each 'cell' is a donor-condition-celltype pseudobulk profile
head(Cells(pseudo_ppfe))
```

```{r}
pseudo_ppfe$CelltypeID.dis <- paste(pseudo_ppfe$Celltype_ID_coarse_heat, pseudo_ppfe$disease.ident, sep = "_")

pseudo_ppfe$CelltypeID.dis %>%unique()

Idents(pseudo_ppfe) <- "CelltypeID.dis"

# DE vs. IPF
Adventitial_DE_vIPF <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Adventitial-Fb_PPFE", 
                         ident.2 = "Adventitial-Fb_IPF",
                         test.use = "DESeq2")
saveRDS(Adventitial_DE_vIPF, "Adventitial_DE_vs_IPF.rds")

# DE vs. IPF
AlvFb_DE_vIPF <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Alveolar-Fb_PPFE", 
                         ident.2 = "Alveolar-Fb_IPF",
                         test.use = "DESeq2")
saveRDS(AlvFb_DE_vIPF, "AlvFb_DE_vsIPF.rds")

# DE vs. IPF
Adventitial_like_DE_vIPF <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Adventitial-like-Fb_PPFE", 
                         ident.2 = "Adventitial-like-Fb_IPF",
                         test.use = "DESeq2")

saveRDS(Adventitial_like_DE_vIPF, "Adventitial_like_DE_vsIPF.rds")

#DE vs. IPF
Subpleural_DE_vIPF <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Subpleural-Fb_PPFE", 
                         ident.2 = "Subpleural-Fb_IPF",
                         test.use = "DESeq2")

saveRDS(Subpleural_DE_vIPF, "Subpleural_DE_vsIPF.rds")

```

```{r}
pseudo_ppfe$CelltypeID.dis <- paste(pseudo_ppfe$Celltype_ID_coarse_heat, pseudo_ppfe$disease.ident, sep = "_")

pseudo_ppfe$CelltypeID.dis %>%unique()

Idents(pseudo_ppfe) <- "CelltypeID.dis"

Adventitial_DE <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Adventitial-Fb_PPFE", 
                         ident.2 = "Adventitial-Fb_CTRL",
                         test.use = "DESeq2")
AlvFb_DE <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Alveolar-Fb_PPFE", 
                         ident.2 = "Alveolar-Fb_CTRL",
                         test.use = "DESeq2")
Adventitial_like_DE <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Adventitial-like-Fb_PPFE", 
                         ident.2 = "Adventitial-like-Fb_CTRL",
                         test.use = "DESeq2")

Subpleural_DE <- FindMarkers(object = pseudo_ppfe, group.by = "CelltypeID.dis",
                         ident.1 = "Subpleural-Fb_PPFE", 
                         ident.2 = "Subpleural-Fb_CTRL",
                         test.use = "DESeq2")

Adventitial_DE$gene <- rownames(Adventitial_DE)

head(Adventitial_DE, n = 15)

```
### Define mes gene of interest
```{r}
#mes_genes_oi <- 
  
mes_genes_oi <- c("CXCL14",  
                  "COL13A1" ,  
                  "LOX"  , 
                  "STEAP2",
                  #"TLR4"   , 
                  "CXCL12" ,  
                  "COL14A1" ,
                  "LEPR"  ,  
                  "SPRY1"  , 
                  "GREM1" ,  
                  #"ELN"  ,  
                  #"FBLN1",
                  #"FBLN2", 
                  #"FBLN1", 
                  "SFRP1" ,   "SFRP2" , 
                  "EFEMP1"  , 
                  "CXCL2"   , 
                  "CCL2" ,
                  "SPRY1" , 
                  #"CTSA", "CPD", 
                  "LTBP4",
                  "IGF1", 
                  #"GLB1",
                  #"TGFB1",
                  "LOX",
                  "FBN1", 
                  "LUM", "DCN", "BGN", 
                  "SPARCL1",
                  "INHBA", 
                  "IFNAR1", 
                  "PRCP", 
                  "PDGFRA",
                  #"MGP", 
                  "MMP2", 
                  "FBXL3")
```


```{r, fig.height=10, fig.width=11}
Subpleural_DE$gene <- rownames(Subpleural_DE)
Subpleural_DE %>% drop_na() -> temp 
p <- EnhancedVolcano(temp, lab = temp$gene, selectLab = mes_genes_oi[mes_genes_oi!="CCL2" &  
                                                                    mes_genes_oi!="CXCL2" &  
                                                                    mes_genes_oi!="INHBA"  &  
                                                                    mes_genes_oi!="FBN1"  &  
                                                                    mes_genes_oi!="MMP2"  &  
                                                                    #mes_genes_oi!="GREM1"   &  
                                                                    mes_genes_oi!="SPRY1"   &  
                                                                    mes_genes_oi!="STEAP2"],
                       
                                    x = 'avg_log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 1.5,
                                    title = paste0(""),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 1.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 0.5, 
                                    #lengthConnectors = unit(0.05,"in"), 
                                    min.segment.length =0.05,
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 1.5,
                                    labSize = 3, max.overlaps = Inf)+theme_scp()+
  NoLegend()+
  theme(
        plot.background = element_rect(fill = "white", colour = "white"),  # Set plot background to white
        panel.background = element_rect(fill = "white", colour = "white"), # Set panel background to white
        strip.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank() # Remove minor grid lines) # Ensure strip background is also white
        )->p

    

p

pdf(file.path(folder, "Subpl_DE_Volcano_DEGs.pdf"), height = 6, width = 6)
#pdf(file = "PPFE_Mesenchyme_subject_Disease_UMAP.pdf", width = 14, height = 7)
p+xlim(-5,5)
dev.off()
```




```{r, fig.height=10, fig.width=10}

Adventitial_DE$gene <- rownames(Adventitial_DE)
Adventitial_DE %>% drop_na() -> temp 
EnhancedVolcano(temp, lab = temp$gene, selectLab = c(mes_genes_oi[mes_genes_oi!="CCL2" &  
                                                                    mes_genes_oi!="CXCL2" &  
                                                                    mes_genes_oi!="INHBA"  &  
                                                                    mes_genes_oi!="EFEMP1"  &  
                                                                    mes_genes_oi!="CXCL12"  &  
                                                                    mes_genes_oi!="GREM1"   &  
                                                                    mes_genes_oi!="SFRP1"   &  
                                                                    mes_genes_oi!="COl14A1"]),
                       
                                    x = 'avg_log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 1.5,
                                    title = paste0(""),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 1.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 0.5, 
                                    #lengthConnectors = unit(0.05,"in"), 
                                    min.segment.length =0.05,
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 1.5,
                                    labSize = 3, max.overlaps = Inf)+theme_scp()+
  NoLegend()+
  theme(
        plot.background = element_rect(fill = "white", colour = "white"),  # Set plot background to white
        panel.background = element_rect(fill = "white", colour = "white"), # Set panel background to white
        strip.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank() # Remove minor grid lines) # Ensure strip background is also white
        )->p

pdf(file.path(folder, "Adv_DE_Volcano_DEGs.pdf"), height = 6, width = 6)
#pdf(file = "PPFE_Mesenchyme_subject_Disease_UMAP.pdf", width = 14, height = 7)
p+xlim(-5,5)
dev.off()
```
```{r, fig.height=10, fig.width=10}
AlvFb_DE$gene <- rownames(AlvFb_DE)
AlvFb_DE %>% drop_na() -> temp 
p <- EnhancedVolcano(temp, lab = temp$gene, selectLab = mes_genes_oi[mes_genes_oi!="LTBP4" &  mes_genes_oi!="FBN1" &  mes_genes_oi!="IFNAR1"  &  mes_genes_oi!="BGN"  &  mes_genes_oi!="EFEMP1"],
                       
                                     x = 'avg_log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 1,
                                    title = paste0(""),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 1.0,
                                    col = c('grey20', 'grey50', 'lightgrey',"#A6CEE3"),
                                    drawConnectors = T,
                                    widthConnectors = 0.5, 
                                    #lengthConnectors = unit(0.05,"in"), 
                                    min.segment.length =0.05,
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 1.5,
                                    labSize = 3, max.overlaps = Inf)+theme_scp()+
  NoLegend()+
  theme(
        plot.background = element_rect(fill = "white", colour = "white"),  # Set plot background to white
        panel.background = element_rect(fill = "white", colour = "white"), # Set panel background to white
        strip.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank() # Remove minor grid lines) # Ensure strip background is also white
        )+
   xlim(-5,5)->p
    

p
pdf(file.path(folder, "AlvFb_DE_Volcano_DEGs.pdf"), height = 7, width = 7)
#pdf(file = "PPFE_Mesenchyme_subject_Disease_UMAP.pdf", width = 14, height = 7)
p
dev.off()

writexl::write_xlsx(temp, "PPFE_Fig2_Pseudobulk_AlveolarFb.xlsx")
```

```{r, fig.height=10, fig.width=10}
Adventitial_like_DE$gene <- rownames(Adventitial_like_DE)
Adventitial_like_DE %>% drop_na() -> temp 
EnhancedVolcano(temp, lab = temp$gene, selectLab = c(mes_genes_oi, "GSN"),
                       
                                    x = 'avg_log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 1.5,
                                    title = paste0("Adventitial-like Fb", ' PPFE vs CTRL'),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 1.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 1.0, 
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 1.5,
                                    labSize = 3.0, max.overlaps = Inf
                      )+theme_scp() ->p
    

p+ylim(0,10)
```


```{r}
library(openxlsx)
library(dplyr)
library(EnhancedVolcano)
library(ggplot2)

# Get unique cell types
celltypes <- unique(pseudo_ppfe$CelltypeID.dis)
common_celltypes <- PPFE_mes$Celltype %>% levels()
# Extract common cell type names without condition suffix (_CTRL or _PPFE)
common_celltypes <- unique(gsub("_(CTRL|PPFE|IPF)$", "", celltypes))
common_celltypes
common_celltypes <- c( "Alveolar-Fb", "Airway-Fb", "Smooth-Muscle",  "Pericytes","Subpleural-Fb", "CTHRC1-MyoFb", "Adventitial-like-Fb", "Adventitial-Fb")
```


# Comparison DE Gene Analysis vs. IPF
```{r, fig.height=10, fig.width=11}
Adventitial_DE_vIPF$gene <- rownames(Adventitial_DE_vIPF)
Adventitial_DE_vIPF %>% drop_na() %>%
  filter(pct.1 > 0 & pct.2 >0)-> temp 
p <- EnhancedVolcano(temp, lab = temp$gene, selectLab = mes_genes_oi,#[mes_genes_oi!="CCL2" &  mes_genes_oi!="CXCL2" & mes_genes_oi!="INHBA"  &  mes_genes_oi!="FBN1"  & mes_genes_oi!="MMP2"  &  #mes_genes_oi!="GREM1"   &  mes_genes_oi!="SPRY1"   &  mes_genes_oi!="STEAP2"],
                       
                                    x = 'avg_log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 2.5,
                                    title = paste0(""),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 1.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 0.5, 
                                    #lengthConnectors = unit(0.05,"in"), 
                                    min.segment.length =0.05,
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 1.5,
                                    labSize = 3, max.overlaps = Inf)+theme_scp()+
  NoLegend()+
  theme(
        plot.background = element_rect(fill = "white", colour = "white"),  # Set plot background to white
        panel.background = element_rect(fill = "white", colour = "white"), # Set panel background to white
        strip.background = element_rect(fill = "white", colour = "white"),
        panel.grid.major = element_blank(),  # Remove major grid lines
        panel.grid.minor = element_blank() # Remove minor grid lines) # Ensure strip background is also white
        )->p

    

p

pdf(file.path(folder, "Subpl_DE_Volcano_DEGs_vs_IPF.pdf"), height = 6, width = 6)
#pdf(file = "PPFE_Mesenchyme_subject_Disease_UMAP.pdf", width = 14, height = 7)
p+xlim(-5,5)
dev.off()
```











#============

```{r}
# Create a new Excel workbook
wb <- createWorkbook()

# Loop through each common cell type and compare PPFE vs CTRL
for (celltype in common_celltypes) {
  ident_ppfe <- paste0(celltype, "_PPFE")
  ident_ctrl <- paste0(celltype, "_CTRL")
  
  if (ident_ppfe %in% celltypes & ident_ctrl %in% celltypes) {
    # Perform differential expression analysis
    de_result <- FindMarkers(
      object = pseudo_ppfe, 
      ident.1 = ident_ppfe, 
      ident.2 = ident_ctrl, 
      test.use = "DESeq2", 
    )
    
    # Order results by avg_log2FC in descending order
    de_result <- de_result %>%
      arrange(desc(avg_log2FC)) 
    de_result$gene <- rownames(de_result)
    
    # Store the result in the Excel workbook
    addWorksheet(wb, sheetName = paste0(celltype, "_DEG"))
    writeData(wb, sheet = paste0(celltype, "_DEG"), de_result)
    
    # Generate and save the volcano plot
    volcano_plot <- EnhancedVolcano(de_result,
                                    lab = rownames(de_result),
                                    x = 'avg_log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 0.5,
                                    title = paste0(celltype, ' PPFE vs CTRL'),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 4.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    pointSize = 2.0,
                                    labSize = 3.0)
    
    # Save the volcano plot as PNG
    ggsave(filename = paste0("Volcano_", celltype, "_PPFE_vs_CTRL.png"),
           plot = volcano_plot,
           width = 8, height = 6, dpi = 300)
  } else {
    message(paste("Skipping", celltype, ": one or both conditions missing"))
  }
}

# Save the Excel workbook
saveWorkbook(wb, file = "All_DE_Results_By_Celltype.xlsx", overwrite = TRUE)

print("Differential expression and volcano plot generation completed.")


```



#=====================

## Pseudobulk DE_Seq_2
```{r}
#BiocManager::install("ExperimentHub")
library(ExperimentHub)
#BiocManager::install("DESeq2")
library(DESeq2)
library(tidyverse)
#install.packages("dbplyr")
library(dbplyr)
library(Seurat)

# pseudo-bulk workflow -----------------
# Acquiring necessary metrics for aggregation across cells in a sample
# 1. counts matrix - sample level
# counts aggregate to sample level

```

```{r}
PPFE <- test_clean
rm(test_clean)

PPFE <- subset(PPFE_mes, disease.ident != "IPF")

PPFE$cell_ident <- rownames(PPFE@meta.data)
PPFE$cell_ident <- sub("^", "_", rownames(PPFE@meta.data))

PPFE$samples <- paste0(PPFE$disease.ident, PPFE$cell_ident)

DefaultAssay(PPFE) <- "RNA"
DefaultAssay(PPFE)

# Impute pseudo-Count
#PPFE[["RNA"]]@counts <- as.matrix(PPFE[["RNA"]]@counts)+1


cts <- AggregateExpression(PPFE, 
                    group.by = c("disease.ident", "orig.ident_final"),
                    assays = 'RNA', #being the "DefaultAssay(KRT6A_Proliferating)"
                    slot = "counts",
                    return.seurat = FALSE)

cts <- cts$RNA

# transpose
cts.t <- t(cts)


# convert to data.frame
cts.t <- as.data.frame(cts.t)

# get values where to split
splitRows <- gsub('_.*', '', rownames(cts.t)) #removed quasi alles nach Unterstrich


# split data.frame
cts.split <- split.data.frame(cts.t,
                 f = factor(splitRows))


# fix colnames and transpose
cts.split.modified <- lapply(cts.split, function(x){
  #rownames(x) <- gsub('.*_(.*)', '\1', rownames(x))
  t(x)
  
})

saveRDS(cts.split.modified, "mes_Pseudobulk_Matrix_pseudocount.rds")
cts.split.modified <- readRDS("mes_Pseudobulk_Matrix_pseudocount.rds")
#gsub('.*_(.*)', '\1', 'B cells_ctrl101')
```


#### All 
```{r}
names(cts.split.modified)
```

```{r}
library(DESeq2)
# 2. generate sample level metadata

cts <- t(cts.t)

colData <- data.frame(samples = colnames(cts))

colData <- colData %>%
  mutate(condition = ifelse(grepl('PPFE', samples), 'PPFE', 'CTRL')) %>%
  column_to_rownames(var = 'samples')

# get more information from metadata# get samplesmore information from metadata




# perform DESeq2 --------
# Create DESeq2 object   
dds <- DESeqDataSetFromMatrix(countData = cts,
                       colData = colData,
                       design = ~ condition)

# filter
keep <- rowSums(counts(dds)) >=10
dds <- dds[keep,]

# run DESeq2
dds <- DESeq(dds, parallel = T)



# Check the coefficients for the comparison
resultsNames(dds)

# Generate results object
res <- results(dds, name = "condition_PPFE_vs_CTRL")

head(as.data.frame(res))


# Changing rownames to extra column for better searching
res_2_with_genes <- tibble::rownames_to_column(as.data.frame(res), "gene")
view(res_2_with_genes)

rownames(res_2_with_genes) <- res_2_with_genes$gene

res_2_with_genes <- res_2_with_genes[!grepl("MT-", res_2_with_genes$gene), ]

saveRDS(res_2_with_genes, "mes_pseudobulk.rds")
```

```{r, fig.height=10, fig.width=14}
library(EnhancedVolcano)
# Generate and save the volcano plot
res_2_with_genes -> tmp
  
 p <- EnhancedVolcano(tmp, lab = tmp$gene,
                       # c("SCGB3A2", "SCGB3A1", "CTSE", "GLUL", "BPIFB1", "DSTN", "KRT15", "SCGB1A1", "LOX", "CDH2", "MMP1", "MMP10", "BPIFA1"),
                                    x = 'log2FoldChange',
                                    y = 'padj',
                                    pCutoff = 0.000005,
                                    FCcutoff = 2.5,
                                    title = paste0("Epithelium", ' PPFE vs CTRL'),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 4.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 2.0, 
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 4.0,
                                    labSize = 4.0, max.overlaps = Inf
                      )+theme_scp()
    

p
 png("Volcano_DE_DEseqPseudobulk_MES_baseMean200_DErecMultiNiche.png", units = "in", res = 1200, width = 12, height = 10)  
p
dev.off()

```



```{r}
library(enrichplot)
library(enrichR)

# Enrichment analysis
listEnrichrSites()
setEnrichrSite("Enrichr")
websiteLive <- TRUE
dbs <- c("BioPlanet_2019", "MSigDB_Hallmark_2020", "GO_Biological_Process_2021", "GO_Cellular_Component_2021", "GO_Molecular_Function_2021") # selecting the libraies of interest
# IPF vs CNT DEGs
enriched <- enrichr(tmp$gene[tmp$log2FoldChange>0.5], dbs) # UP - 0.5 FC FILT
exp<-enriched$BioPlanet_2019
exp$Ref<-c("BioPlanet")
exp_temp<-enriched$MSigDB_Hallmark_2020
exp_temp$Ref<-c("MSigDB")
exp<-rbind(exp, exp_temp)
exp_temp<-enriched$GO_Biological_Process_2021
exp_temp$Ref<-c("GO_BP")
exp<-rbind(exp, exp_temp)
exp_temp<-enriched$GO_Cellular_Component_2021
exp_temp$Ref<-c("GO_CC")
exp<-rbind(exp, exp_temp)
exp_temp<-enriched$GO_Molecular_Function_2021
exp_temp$Ref<-c("GO_MF")
exp<-rbind(exp, exp_temp)
exp$cluster<-c("UP")

enriched2 <- enrichr(tmp$gene[tmp$log2FoldChange< -0.5], dbs) # DOWN - 0.5 FC FILT
exp2<-enriched2$BioPlanet_2019
exp2$Ref<-c("BioPlanet")
exp_temp2<-enriched2$MSigDB_Hallmark_2020
exp_temp2$Ref<-c("MSigDB")
exp2<-rbind(exp2, exp_temp2)
exp_temp2<-enriched2$GO_Biological_Process_2021
exp_temp2$Ref<-c("GO_BP")
exp2<-rbind(exp2, exp_temp2)
exp_temp2<-enriched2$GO_Cellular_Component_2021
exp_temp2$Ref<-c("GO_CC")
exp2<-rbind(exp2, exp_temp2)
exp_temp2<-enriched2$GO_Molecular_Function_2021
exp_temp2$Ref<-c("GO_MF")
exp2<-rbind(exp2, exp_temp2)
exp2$cluster<-c("DOWN")
exp<-rbind(exp, exp2)

exp_enrich<-subset(exp, exp$Adjusted.P.value<0.01)
# Count how many gene elements per term
exp_enrich$temp<-gsub(";", "", exp_enrich$Genes)
exp_enrich$num<-(nchar(exp_enrich$Genes)-nchar(exp_enrich$temp)) + 1
exp_enrich$temp<-NULL
writexl::write_xlsx(exp_enrich, "AEC1_PPFE_vs_CTRL_macro_enrich_by_pseudobulkgenes.xlsx")

temp<-subset(exp_enrich, cluster == "UP")# & Combined.Score>150)
neworder<-data.frame(Term=temp$Term, score=-log(temp$Adjusted.P.value))
neworder<-aggregate(. ~Term, neworder, sum)
neworder<-neworder[order(neworder$score, decreasing = F),]
temp$x<-factor(temp$Term, levels =neworder$Term)
temp<-subset(temp, is.na(temp$x)==F)
temp<-droplevels(temp)
ggplot(temp, aes(-log(Adjusted.P.value), x, fill=Combined.Score)) + geom_col(position = "stack") + theme_scp() + theme(axis.text.y = element_text(size=rel(1), color = "black", face = "bold"), legend.position = "none", legend.title=element_blank()) + ylab(NULL) + xlab("MSigDB Score")+ scale_fill_viridis_b()
```











```{r, fig.width=5, fig.height=7}
library(Seurat)
library(dplyr)
library(ggplot2)

# Step 1: Extract MMP7 expression, Disease condition, and subject info
average_expression <- FetchData(subset(PPFE, Celltype_ID_final_coarse == "AEC1"), vars = c("BMP2", "orig.ident", "disease.ident")) %>%
  group_by(orig.ident, disease.ident) %>%  # Group by subject and disease
  summarize(Average_Expression = mean(BMP2)) %>% # Calculate mean
  ungroup()

# Step 2: Plot as a boxplot
ggplot(average_expression, aes(x = disease.ident, y = Average_Expression, fill = disease.ident)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, aes(color = "black"), colour = "black") +  # Data points for each subject
  labs(
    title = "Average BMP2 Expression per Subject by Condition",
    x = "Condition",
    y = "Average BMP2 Expression"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "red3"))+theme_scp() 


# Step 1: Extract MMP7 expression, Disease condition, and subject info
average_expression <- FetchData(subset(PPFE, Celltype_ID_final_coarse == "AEC1"), vars = c("CTSE", "orig.ident", "disease.ident")) %>%
  group_by(orig.ident, disease.ident) %>%  # Group by subject and disease
  summarize(Average_Expression = mean(CTSE)) %>% # Calculate mean
  ungroup()

# Step 2: Plot as a boxplot
ggplot(average_expression, aes(x = disease.ident, y = Average_Expression, fill = disease.ident)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, aes(color = "black"), colour = "black") +  # Data points for each subject
  labs(
    title = "Average CTSE Expression per Subject by Condition",
    x = "Condition",
    y = "Average CTSE Expression"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "red3"))+theme_scp() 

# Step 1: Extract MMP7 expression, Disease condition, and subject info
average_expression <- FetchData(PPFE, vars = c("TGFB2", "orig.ident", "disease.ident")) %>%
  group_by(orig.ident, disease.ident) %>%  # Group by subject and disease
  summarize(Average_Expression = mean(TGFB2)) %>% # Calculate mean
  ungroup()

# Step 2: Plot as a boxplot
ggplot(average_expression, aes(x = disease.ident, y = Average_Expression, fill = disease.ident)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, aes(color = "black"), colour = "black") +  # Data points for each subject
  labs(
    title = "Average TGFB2 Expression per Subject by Condition",
    x = "Condition",
    y = "Average TGFB2 Expression"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "red3"))+theme_scp() 

# Step 1: Extract MMP7 expression, Disease condition, and subject info
average_expression <- FetchData(PPFE, vars = c("CXCL12", "orig.ident", "disease.ident")) %>%
  group_by(orig.ident, disease.ident) %>%  # Group by subject and disease
  summarize(Average_Expression = mean(CXCL12)) %>% # Calculate mean
  ungroup()

# Step 2: Plot as a boxplot
ggplot(average_expression, aes(x = disease.ident, y = Average_Expression, fill = disease.ident)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, aes(color = "black"), colour = "black") +  # Data points for each subject
  labs(
    title = "Average CXCL12 Expression per Subject by Condition",
    x = "Condition",
    y = "Average CXCL12 Expression"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "red3"))+theme_scp() 

```

### Loop for each celltype
```{r}
library(DESeq2)
library(tibble)
library(dplyr)
library(EnhancedVolcano)
library(ggplot2)

# List of cell types
cell_types <- c("Aberrant-Basaloid", "AEC-intermediate", "AEC1", "AEC2", 
                "Basal", "Ciliated", "Club", "Goblet", "PNEC", "Secretory")
cell_types <- c("Secretory")

# Input: cts.split.modified (list of count matrices per cell type)

# Loop through each cell type
for (cell_type in cell_types) {
  
  cat("Processing:", cell_type, "\n")  # Log progress
  
  # Create a folder for the current cell type
  output_dir <- paste0(cell_type, "_results")
  dir.create(output_dir, showWarnings = FALSE)  # Create folder if it doesn't exist
  
  # 1. Load counts for the current cell type
  cts <- cts.split.modified[[cell_type]]
  
  # 2. Create sample metadata
  colData <- data.frame(samples = colnames(cts)) %>%
    mutate(condition = ifelse(grepl('PPFE', samples), 'PPFE', 'CTRL')) %>%
    column_to_rownames(var = 'samples')
  
  # 3. DESeq2 object creation
  dds <- DESeqDataSetFromMatrix(countData = cts,
                                colData = colData,
                                design = ~ condition)
  
  # 4. Filtering low counts
  keep <- rowSums(counts(dds)) >= 10
  dds <- dds[keep, ]
  
  # 5. Run DESeq2
  dds <- DESeq(dds, parallel = TRUE)
  
  # 6. Extract results
  res <- results(dds, name = "condition_PPFE_vs_CTRL")
  
  # 7. Add gene names as a column and remove mitochondrial genes
  res_with_genes <- rownames_to_column(as.data.frame(res), "gene") %>%
    filter(!grepl("^MT-", gene))  # Exclude mitochondrial genes
  
  # 8. Save results as RDS
  saveRDS(res_with_genes, file.path(output_dir, paste0(cell_type, "_pseudobulk.rds")))
  
  # 9. Generate and save the volcano plot
  volcano_plot <- EnhancedVolcano(
    res_with_genes,
    lab = res_with_genes$gene,
    x = 'log2FoldChange',
    y = 'padj',
    pCutoff = 0.05,
    FCcutoff = 0.5,
    title = paste0(cell_type, " PPFE vs CTRL"),
    subtitle = '',
    legendPosition = 'right',
    legendLabSize = 12,
    legendIconSize = 4.0,
    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
    pointSize = 2.0,
    labSize = 3.0
  )
  
  # Save the volcano plot as PNG
  ggsave(
    filename = file.path(output_dir, paste0("Volcano_", cell_type, "_PPFE_vs_CTRL.png")),
    plot = volcano_plot,
    width = 8, height = 6, dpi = 300
  )
  
  cat("Finished processing:", cell_type, "\n")  # Log completion
}

```


```{r}
FeatureDimPlot(test_clean, features = "CTHRC1", assay = "RNA", pt.size = 2)
```

#=====================================
# DE Marker Genes Mesenchyme

# Per Subject
```{r}
myMultithreadFindMarkersDOR <- function(seurat.object, group.name, subject.ident, logFC.min.filter, ncores) {
    library(parallel)
    seurat.object$cellBarcode <- colnames(seurat.object)
    num.cellsTotal <- nrow(seurat.object@meta.data)
    group.levels <- as.vector(unique(seurat.object@meta.data[[group.name]]))
    subject.levels <- as.vector(unique(seurat.object@meta.data[[subject.ident]]))
    
    # Multithread function
    MultithreadFindMarkersDOR <- function(x) {
        temp.cells <- seurat.object@meta.data %>%
            filter(seurat.object@meta.data[[group.name]] == x) %>%
            pull(cellBarcode)
        
        # Calculate per-subject averages for in-group and out-group
        subject.mean.exp <- lapply(subject.levels, function(subj) {
            subj.cells <- seurat.object@meta.data %>%
                filter(seurat.object@meta.data[[subject.ident]] == subj) %>%
                pull(cellBarcode)
            inGroup.cells <- intersect(temp.cells, subj.cells)
            outGroup.cells <- setdiff(subj.cells, temp.cells)
            
            avgExp.inGroup <- if (length(inGroup.cells) > 0) {
                rowMeans(seurat.object@assays$RNA@data[, inGroup.cells, drop = FALSE])
            } else {
                rep(0, nrow(seurat.object@assays$RNA@data))
            }
            
            avgExp.outGroup <- if (length(outGroup.cells) > 0) {
                rowMeans(seurat.object@assays$RNA@data[, outGroup.cells, drop = FALSE])
            } else {
                rep(0, nrow(seurat.object@assays$RNA@data))
            }
            
            list(avgExp.inGroup = avgExp.inGroup, avgExp.outGroup = avgExp.outGroup)
        })
        
        temp.avgExpAllGenes.inGroup <- Reduce("+", lapply(subject.mean.exp, `[[`, "avgExp.inGroup")) / length(subject.levels)
        temp.avgExpAllGenes.outGroup <- Reduce("+", lapply(subject.mean.exp, `[[`, "avgExp.outGroup")) / length(subject.levels)
        
        temp.all.logFC <- temp.avgExpAllGenes.inGroup - temp.avgExpAllGenes.outGroup
        temp.filt.logFC <- temp.all.logFC[temp.all.logFC >= logFC.min.filter]
        temp.numGenesFilt <- length(temp.filt.logFC)
        
        cat("Computing statistics for ", temp.numGenesFilt, " genes for ", x, ".\n", sep = "")
        
        num.cellsInGroup <- length(temp.cells)
        num.cellsOutGroup <- num.cellsTotal - num.cellsInGroup
        
        num.TruePos <- rowSums(seurat.object@assays$RNA@data[names(temp.filt.logFC), temp.cells] > 0)
        num.FalsePos <- rowSums(seurat.object@assays$RNA@data[names(temp.filt.logFC), !colnames(seurat.object@assays$RNA@data) %in% temp.cells] > 0)
        
        num.FalseNeg <- num.cellsInGroup - num.TruePos
        num.TrueNeg <- num.cellsOutGroup - num.FalsePos
        
        temp.logDOR <- log((num.TruePos + 0.5) / (num.FalsePos + 0.5) / ((num.FalseNeg + 0.5) / (num.TrueNeg + 0.5)))
        
        temp.data <- seurat.object@assays$RNA@data[names(temp.filt.logFC), ]
        p_val <- sapply(1:nrow(temp.data), function(x) {
            wilcox.test(x = temp.data[x, temp.cells],
                        y = temp.data[x, seurat.object$cellBarcode[!seurat.object$cellBarcode %in% temp.cells]])$p.value
        })
        names(p_val) <- names(temp.filt.logFC)
        p_val_adj <- p.adjust(p = p_val, method = "bonferroni", n = nrow(seurat.object))
        
        temp.df <- data.frame(
            group.name = rep(x, temp.numGenesFilt),
            gene = names(temp.filt.logFC),
            logFC = temp.filt.logFC,
            logDOR = temp.logDOR,
            pct.1 = num.TruePos / num.cellsInGroup,
            pct.2 = num.FalsePos / num.cellsOutGroup,
            p_val = p_val,
            p_val_adj = p_val_adj,
            nCells.in = num.cellsInGroup,
            nCells.out = num.cellsOutGroup
        )
        colnames(temp.df)[colnames(temp.df) == "group.name"] <- group.name
        
        return(temp.df %>% arrange(desc(logDOR)))
    }
    
    outputList <- parallel::mclapply(group.levels, MultithreadFindMarkersDOR, mc.cores = ncores)
    return(Reduce(rbind, outputList))
}

### Mesencvhyme
mes.markers.DOR_subject <- myMultithreadFindMarkersDOR(
    seurat.object=PPFE_mes,
    subject.ident = "orig.ident_final",
    group.name="Celltype_ID_coarse",
    logFC.min.filter=0.25, 
    ncores=1)

writexl::write_xlsx(mes.markers.DOR, "MES_MARKERS_FINAL_per_SUBJECT.xlsx")
```
```{r}
PPFE_mes$orig.ident_final %>% unique()

PPFE_mes$Celltype_ID_coarse %>% unique()
```


# per Subject Celltype and Disease 
```{r}
myMultithreadFindMarkersDOR <- function(seurat.object, group.name, subject.ident, disease, logFC.min.filter, pval.filter = 0.05, ncores) {
    library(future.apply)
    plan(multisession, workers = ncores)  # Set up parallel processing
    
    seurat.object$cellBarcode <- colnames(seurat.object)
    num.cellsTotal <- nrow(seurat.object@meta.data)
    group.levels <- as.vector(unique(seurat.object@meta.data[[group.name]]))
    disease.levels <- as.vector(unique(seurat.object@meta.data[[disease]]))
    subject.levels <- as.vector(unique(seurat.object@meta.data[[subject.ident]]))
    pseudocount <- 1e-5  # Small pseudocount to avoid log(0)
    
    # Multithread function
    MultithreadFindMarkersDOR <- function(celltype) {
        cat("Processing cell type:", celltype, "\n")
        
        temp.cells <- seurat.object@meta.data %>%
            filter(seurat.object@meta.data[[group.name]] == celltype) %>%
            pull(cellBarcode)
        
        # Calculate expression by subject and disease
        disease.subject.exp <- lapply(disease.levels, function(dis) {
            dis.cells <- seurat.object@meta.data %>%
                filter(seurat.object@meta.data[[disease]] == dis) %>%
                pull(cellBarcode)
            dis.subject.exp <- lapply(subject.levels, function(subj) {
                subj.cells <- intersect(dis.cells, 
                                        seurat.object@meta.data %>% filter(seurat.object@meta.data[[subject.ident]] == subj) %>% pull(cellBarcode))
                inGroup.cells <- intersect(temp.cells, subj.cells)
                
                avgExp.inGroup <- if (length(inGroup.cells) > 0) {
                    rowMeans(seurat.object@assays$RNA@data[, inGroup.cells, drop = FALSE])
                } else {
                    rep(0, nrow(seurat.object@assays$RNA@data))
                }
                list(subject = subj, avgExp.inGroup = avgExp.inGroup)
            })
            names(dis.subject.exp) <- subject.levels
            dis.subject.exp
        })
        names(disease.subject.exp) <- disease.levels

        # Filter genes based on log2FC before Wilcoxon test
        filtered_genes <- lapply(rownames(seurat.object@assays$RNA@data), function(gene) {
            expression_by_disease <- lapply(disease.levels, function(dis) {
                sapply(disease.subject.exp[[dis]], function(subj) subj$avgExp.inGroup[gene] + pseudocount)
            })
            
            # Calculate log2FC
            mean_exp_disease1 <- mean(expression_by_disease[[1]], na.rm = TRUE)
            mean_exp_disease2 <- mean(expression_by_disease[[2]], na.rm = TRUE)
            log2FC <- log2(mean_exp_disease2) - log2(mean_exp_disease1)
            
            # Keep only genes with sufficient log2FC
            if (!is.na(log2FC) && abs(log2FC) >= logFC.min.filter) {
                list(gene = gene, log2FC = log2FC, expression_by_disease = expression_by_disease)
            } else {
                NULL
            }
        })
        filtered_genes <- filtered_genes[!sapply(filtered_genes, is.null)]

        # Perform Wilcoxon test on filtered genes
        if (length(filtered_genes) > 0) {
            wilcox_results <- lapply(filtered_genes, function(gene_info) {
                p_val <- wilcox.test(
                    gene_info$expression_by_disease[[1]],
                    gene_info$expression_by_disease[[2]],
                    exact = FALSE
                )$p.value
                data.frame(gene = gene_info$gene, p_val = p_val, log2FC = gene_info$log2FC)
            })
            
            # Combine results into a data frame
            results <- do.call(rbind, wilcox_results)
            results$p_val_adj <- p.adjust(results$p_val, method = "bonferroni")
            
            # Filter by adjusted p-value
            significant_results <- results[results$p_val_adj <= pval.filter, , drop = FALSE]
            
            # Add celltype column only if results are not empty
            if (nrow(significant_results) > 0) {
                significant_results$celltype <- celltype
            }
            return(significant_results)
        } else {
            return(NULL)  # Return NULL if no genes pass the filter
        }
    }
    
    outputList <- future_lapply(group.levels, MultithreadFindMarkersDOR)
    final_results <- do.call(rbind, outputList)
    return(final_results)
}





#PPFE_mes_no_IPF <- subset(PPFE_mes, disease.ident != "IPF")
library(future.apply)
results_all <- myMultithreadFindMarkersDOR(
    seurat.object = test_clean,
    group.name = "Celltype_ID_coarse_heat",
    subject.ident = "orig.ident_final",
    disease = "disease.ident",
    logFC.min.filter = 0.0,
    pval.filter = 1,
    ncores = 8
)

results_all %>%
  drop_na() -> results_clean

# Save Workbook
writexl::write_xlsx(results_clean, "mes_DEGs_per_Disease_by_subject_all.xlsx")
# Stop the created clusters from future
future:::ClusterRegistry("stop")


results_clean <-readxl::read_xlsx("mes_DEGs_per_Disease_by_subject_all.xlsx")
```


```{r, fig.width=14, fig.height=14}
library(EnhancedVolcano)
celltype = "Adventitial_like_Fb"

temp <- results_clean %>%
  dplyr::filter(celltype == "Adventitial_like_Fb")

p <- EnhancedVolcano(temp, lab = temp$gene, #selectLab = "CXCL14",
                       # c("SCGB3A2", "SCGB3A1", "CTSE", "GLUL", "BPIFB1", "DSTN", "KRT15", "SCGB1A1", "LOX", "CDH2", "MMP1", "MMP10", "BPIFA1"),
                                    x = 'log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 2,
                                    title = paste0(celltype, ' PPFE vs CTRL'),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 4.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 2.0, 
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 4.0,
                                    labSize = 4.0, max.overlaps = Inf
                      )+theme_scp()
    

p
    # Save the volcano plot as PNG
    ggsave(filename = paste0("Volcano_perSubject", celltype, "_PPFE_vs_CTRL.png"),
           plot = p,
           width = 14, height =14, dpi = 300)
```

```{r, fig.width=14, fig.height=14}
library(EnhancedVolcano)
celltype = "Adventitial_like_Fb"

temp <- results_all %>%
  dplyr::filter(celltype == "Adventitial_like_Fb")

p <- EnhancedVolcano(temp, lab = temp$gene, #selectLab = "BGN",
                       # c("SCGB3A2", "SCGB3A1", "CTSE", "GLUL", "BPIFB1", "DSTN", "KRT15", "SCGB1A1", "LOX", "CDH2", "MMP1", "MMP10", "BPIFA1"),
                                    x = 'log2FC',
                                    y = 'p_val_adj',
                                    pCutoff = 0.05,
                                    FCcutoff = 1.5,
                                    title = paste0(celltype, ' PPFE vs CTRL'),
                                    subtitle = '',
                                    legendPosition = 'right',
                                    legendLabSize = 12,
                                    legendIconSize = 4.0,
                                    col = c('grey30', 'forestgreen', 'royalblue', 'red2'),
                                    drawConnectors = T,
                                    widthConnectors = 2.0, 
                                    colConnectors = 'black', 
                                    boxedLabels = T,
                                    pointSize = 4.0,
                                    labSize = 4.0, max.overlaps = Inf
                      )+theme_scp()
    

p
    # Save the volcano plot as PNG
    ggsave(filename = paste0("Volcano_perSubject", celltype, "_PPFE_vs_CTRL.png"),
           plot = p,
           width = 14, height =14, dpi = 300)
```

## Plot single Genes from DE Analysis
```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("CXCL14", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(CXCL14)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)

ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average CXCL14 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average CXCL14 Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType, scales = "free_y") +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()

```
```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

DefaultAssay(PPFE_mes) <- "RNA"

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("PDGFRA", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(PDGFRA)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


p <- ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average PDGFRA Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average PDGFRA Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", 
    comparisons = list(
      c("Germany__CTRL", "Germany__PPFE"), 
      c("Germany__CTRL", "France__PPFE"), 
      c("Germany__PPFE", "France__PPFE")
    ),
    hide.ns = F
  ) +
  theme_scp() 
p


png(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_PDGFRA_mes_OI.png"), width = 12, height = 12, res = 1200, units = "in")
p
dev.off()
pdf(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_PDGFRA_mes_OI.pdf"), width = 12, height = 12)
p
dev.off()
```
```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("SNCA", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(SNCA)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average SNCA Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average SNCA Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType, scales = "free_y") +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()
```
```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
DefaultAssay(PPFE_mes) <- "RNA"
PPFE_mes$disease.ident_cohort <- factor(PPFE_mes$disease.ident_cohort, levels = c("Germany__CTRL", "France__PPFE", "Germany__PPFE", "IPF__Belgium"))
```


```{r, fig.width=10, fig.height=10}
# Start
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

celltypes
mes_oi <- c("Adventitial_Fb", "Adventitial_like_Fb", "Subpleural_Fb")#,"Alveolar_Fb", "Airway_Fb", "CTHRC1_MyoFb")

# Loop through each cell type
for (celltype in mes_oi) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("CXCL12", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(CXCL12)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


p <- ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average CXCL12 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average CXCL12 Expression per subject"
  ) +
  #theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", 
    comparisons = list(
      c("Germany__CTRL", "Germany__PPFE"), 
      c("Germany__CTRL", "France__PPFE"), 
      c("Germany__PPFE", "France__PPFE")
    ),
    hide.ns = F
  ) +
  theme_scp() 
p


png(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_CXCL12_mes_OI.png"), width = 10, height = 12, res = 1200, units = "in")
p
dev.off()

pdf(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_CXCL12_mes_OI.pdf"), width = 5.5, height = 6)
p
dev.off()
```


```{r, fig.width=7}
final_results$Group <- paste(final_results$CellType, final_results$disease.ident_cohort, sep = "_")

p <- ggplot(final_results, aes(x = Group, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +
  geom_jitter(width = 0.2, size = 2, colour = "black") +
  labs(
    title = "Average CXCL12 Expression per Subject by Condition and Cell Type",
    x = "Cell Type and Condition",
    y = "Average CXCL12 Expression per Subject"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", 
    comparisons = list(
      c("Fibroblast_Germany__CTRL", "Fibroblast_Germany__PPFE"),
      c("Fibroblast_Germany__CTRL", "Fibroblast_France__PPFE"),
      c("Fibroblast_Germany__PPFE", "Fibroblast_France__PPFE")
      # Add more comparisons if you have other cell types
    ),
    hide.ns = FALSE
  ) + theme_scp() + Seurat::RotatedAxis()
p
```

```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()
celltypes
mes_oi <- c("Adventitial_Fb", "Adventitial_like_Fb", "Subpleural_Fb",
            "Alveolar_Fb", "Airway_Fb", "CTHRC1_MyoFb")

# Loop through each cell type
for (celltype in mes_oi) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("CCL2", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(CCL2)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


p <- ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average CCL2 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average CCL2 Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", 
    comparisons = list(
      c("Germany__CTRL", "Germany__PPFE"), 
      c("Germany__CTRL", "France__PPFE"), 
      c("Germany__PPFE", "France__PPFE")
    ),
    hide.ns = F
  ) +
  theme_scp() 
p


png(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_CCL2_mes_OI.png"), width = 10, height = 12, res = 1200, units = "in")
p
dev.off()
pdf(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_CCL2_mes_OI.pdf"), width = 10, height = 12)
p
dev.off()
```





















```{r, fig.width=10, fig.height=10}

PPFE_mes$disease.ident_cohort %>% unique()

PPFE_mes$disease.ident_cohort <- factor(PPFE_mes$disease.ident_cohort, levels = c("Germany__CTRL","France__PPFE", "Germany__PPFE", "IPF__Belgium")
                                        )
```


```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()
celltypes
mes_oi <- c("Adventitial_Fb", "Adventitial_like_Fb", "Subpleural_Fb")

# Loop through each cell type
for (celltype in mes_oi) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("CXCL14", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(CXCL14)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)
final_results

p <- ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average CXCL14 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average CXCL14 Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", 
    comparisons = list(
      c("Germany__CTRL", "Germany__PPFE"), 
      c("Germany__CTRL", "France__PPFE"), 
      c("Germany__PPFE", "France__PPFE")
    ),
    hide.ns = F
  ) +
  theme_scp() 
p

png(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_CXCL14_mes_OI.png"), width = 10, height = 6, res = 1200, units = "in")
p
dev.off()
pdf(file.path("C:\\Users\\Jannik\\OneDrive\\PNE_MHH\\AG_Prasse_OneDrive\\PPFE\\PPFE_Nuc_Seq\\Batch_integration\\ppfe_immune\\Immune_IPF\\Output_Figure7\\Cellchat_","PPFE_CTRL_CXCL14_mes_OI.pdf"), width = 10, height = 6)
p
dev.off()
```

```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("STEAP2", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(STEAP2)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average STEAP2 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average STEAP2 Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType, scales = "free_y") +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()
```

```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("LEPR", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(LEPR)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average LEPR Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average LEPR Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType, scales = "free_y") +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()
```

```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("BGN", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(BGN)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)

ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average BGN Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average BGN Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType, scales = "free_y") +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()

```


```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("BGN", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(BGN)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)

ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average BGN Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average BGN Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType, scales = "free_y") +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()

```

```{r, fig.width=10, fig.height=10}
# Initialize an empty list to store results for each cell type
results_list <- list()
celltypes <- PPFE_mes$Celltype_ID_coarse_heat %>% levels()

# Loop through each cell type
for (celltype in celltypes) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(PPFE_mes, Celltype_ID_coarse_heat == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("LGR5", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(LGR5)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)

ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average LGR5 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average LGR5 Expression per subject"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue","pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  theme_scp() + stat_compare_means()

```