---
title: "Figure_7_Immune"
author: "Jannik Ruwisch"
date: "2025-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.width = 14,
                      fig.height = 7,
                      dev = "png",
                      cache = F)
```

```{r}
library(SCP)
library(Seurat)
library(SeuratObject)
library(dplyr)
library(tidyverse)
library(tidyseurat)
library(ggpubr)
library(rstatix)
library(writexl)

```

# Load Objects
```{r}
# Start from here...
PPFE_lym <- readRDS("./PPFE_Lymphoid_Lineage.rds")
```

# Save Path
```{r}
folder = choose.dir()
```


# Color Palette Settings
```{r}
pal_cluster_scp_pal <- SCP::palette_scp(x = c(
  "Treg",
  "CD4+_TC_naive",
  "CD4+_TC_effector_memory",
  "CD4+_TC_TH1",
  "CD4+_TC_TH17",
  "ILC3",
  "CD4+_TC_Cytotoxic",
  "CD8+_TC_effector_memory",
  "CD8+_TC_resident_memory",
  "gamma_delta_TC", 
  "NK_Cells_CD16-" ,
  "NK_Cells_CD16+",
  "Plasma_Cells",
  "B_Cells_naive",
  "B_Cells_memory"), matched = T,
                                    palette = "Set3")
pal_dis_pal <- palette_scp(x = PPFE_lym$disease.ident%>% unique(), palcolor = c("royalblue", "red3", "#ffd59b"), matched = F)
pal_cohort_pal_heat <- palette_scp(x = c("Germany", "France",  "Belgium"), palcolor = c("grey88", "grey58", "grey18"), matched = F)
pal_cohort_pal <-  c("royalblue", "red1", "darkred", "#ffd59b")
pal_subject_pal <-  palette_scp(palette = "igv", x = PPFE_lym$orig.ident_final %>% unique(), matched = F) 
```

#===============

# Cellfrequency Plot
```{r}
# Refer to separate Rmd File: "./PPFE_figure_7_FreqPlots.Rmd"
```

## Wilcox Rank Sum Test 
```{r}
# Calculate Lineage-wide Frequency Statistics
summary_df <- ggData %>%
  group_by(Celltype_ID, Disease) %>%
  summarise(
    mean_value = mean(value, na.rm = TRUE),
    sd_value = sd(value, na.rm = TRUE)
  ) %>%
  ungroup()
write_xlsx(summary_df, file.path(folder, "PPFE_IPF_Mes_by_celltype_freq_onlyImmune.xlsx"))

wilcox_results <- ggData %>%
  group_by(Celltype_ID) %>%
  wilcox_test(value ~ Disease) %>%
  adjust_pvalue(method = "bonferroni") %>%
  add_significance("p.adj") %>%
  ungroup()

wilcox_results
write_xlsx(wilcox_results, file.path(folder, "PPFE_IPF_Mes_by_celltype_freq_wilcox_onlyImmune.xlsx"))


final_df <- summary_df %>%
  left_join(wilcox_results, by = "Celltype_ID")
final_df

# Export merged DF
write_xlsx(final_df, file.path(folder, "PPFE_IPF_Mes_by_celltype_freq_Wilcox_rank_sum_test_merged_onlyImmune.xlsx"))
```

#===============

# UMAP Plots 

## UMAP_Celltype
```{r}
# Relable Celltype variable 
PPFE_lym$Celltype <- PPFE_lym$Celltype_ID_fine

PPFE_lym$Celltype <- factor(PPFE_lym$Celltype, levels = c(
  "Treg",
  "CD4+_TC_naive",
  "CD4+_TC_effector_memory",
  "CD4+_TC_TH1",
  "CD4+_TC_TH17",
  "ILC3",
  "CD4+_TC_Cytotoxic",
  "CD8+_TC_effector_memory",
  "CD8+_TC_resident_memory",
  "gamma_delta_TC", 
  "NK_Cells_CD16-" ,
  "NK_Cells_CD16+",
  "Plasma_Cells",
  "B_Cells_naive",
  "B_Cells_memory"))

p <- CellDimPlot(PPFE_lym, group.by = "Celltype", raster = F, pt.size = 0.15, reduction = "ReUMAP_18", palcolor = pal_cluster_scp_pal, 
                 show_stat = F, xlab = "UMAP_1", ylab = "UAMP_2", legend.position = "right")+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank(), 
        legend.title =element_text(face = "bold") 
        ) # Remove axis ticks
 
# Export as PDF 
pdf(file = file.path(folder, "Figure_7_PPFE_END_UMAP.pdf"), height = 7, width = 7)
p
dev.off()
```


## UMAP_Disease_Subject
```{r}
p <- DimPlot(PPFE_lym, group.by = c("orig.ident_final"),shuffle = T, raster = F, label = F, combine = T, reduction = "ReUMAP_18", pt.size = 0.01, 
             cols = pal_subject_pal)+
  theme_scp()+NoLegend()+ggtitle("Subject")+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank(), 
        legend.title =element_text(face = "bold")) +
          labs(x = "UMAP_1",  # New label for x-axis
               y = "UMAP_2"   # New label for y-axis
  )|
  DimPlot(PPFE_lym, group.by = c("disease.ident"),shuffle = T, raster = F, label = F, combine = T, reduction = "ReUMAP_18", pt.size = 0.01, cols = pal_dis_pal)+
    theme_scp()+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank(), 
        legend.title =element_text(face = "bold"))+
          labs(x = "UMAP_1",  # New label for x-axis
               y = "UMAP_2"   # New label for y-axis
  )+
  NoLegend()+ggtitle("Disease")
p

pdf(file.path(folder, "Figure7_Disease_Cohort_UMAP.pdf"), height = 7, width = 14)
p
dev.off()

#============================================================

# Plot with legend 
p_leg <- DimPlot(PPFE_lym, group.by = c("orig.ident_final"),shuffle = T, raster = F, label = F, combine = T, reduction = "ReUMAP_18", pt.size = 0.01, 
             cols = pal_subject_pal)+
  theme_scp()+ggtitle("Subject")+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank(), 
        legend.title =element_text(face = "bold")) +
          labs(x = "UMAP_1",  # New label for x-axis
               y = "UMAP_2"   # New label for y-axis
  )|
  DimPlot(PPFE_lym, group.by = c("disease.ident"),shuffle = T, raster = F, label = F, combine = T, reduction = "ReUMAP_18", pt.size = 0.01, cols = pal_dis_pal)+
    theme_scp()+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank(), 
        legend.title =element_text(face = "bold"))+
          labs(x = "UMAP_1",  # New label for x-axis
               y = "UMAP_2"   # New label for y-axis
  )+ggtitle("Disease")

# Export PDF 
pdf(file.path(folder, "Figure7_Disease_Cohort_UMAP_leg.pdf"), height = 7, width = 14)
p_leg
dev.off()
```

#===============

## UnityHeatmap
```{r}
genes_for_heatmap <-  c(
 "FOXP3", 	 "LAYN", 	 "CCR8", 	 "F5", #	Treg
 "TCF7", 	 "LEF1", 	 "CCR7", 	 "SELL", 	#CD4 naiv
 "LINC02694",  	 "RBPJ", 	 "CD4", "CD40LG",# CD4 effector
 	"TBX21",   "SAP30", 	 "CXCR3",  "ALOX5AP",	#Th1
 	 "CCR6", 	 "CXCR6",  "LTK", 	 "KLRB1",	#TH17
 "RORC", "SCN1B", 	 "KIT", 	 "DLL1", 	  	#ILC3
 	 "PDCD1", 	  "GZMK", 	 "GZMA","CCR2", 	#Cytotox
 "CD8A", "CST7",	 "CCL5","CRTAM",  	#CD8+_TC_effector_memory
 "ZNF683", 	 "LAG3", "ITGA1", "TOB1", #CD8+_TC_resident_memory
 "CTSW", "TRDC",	"TRGC1",    #	gamma_delta_TC
 "GNLY","KLRD1", "NCR1", 	 	  "FCER1G",  	#NK_Cells_CD16-
 "FGFBP2", 	 "CX3CR1", 	 "FCGR3A", 	 "LINGO2", #	NK_Cells_CD16+
 "JCHAIN", 	"MZB1",	"XBP1", "IGHG1",    #	Plasma_Cells
 "TCL1A", 	 "IGHD", 	 "FCER2", 	 "IGHM", 	#B_Cells_naive
 "MS4A1", 	 "BLK", 	 "BANK1", 	 "CD79A" 	#B_Cells_memory
 )
```

```{r}
### with multithreading, first make all possible combinations
FullDataset_Object <- PPFE_lym

FullDataset_Object <- FullDataset_Object %>%
  mutate(orig.ident = case_when(Project == "PPFE" ~ orig.ident,
                                  Project == "IPF" ~ substr(orig.ident, start = 1, stop = 10))
       )

FullDataset_Object <- FullDataset_Object %>%
  mutate(Cohort = case_when(Project == "PPFE" ~ Cohort,
                                  Project == "IPF" ~ "Belgium")
       )

celltypes_to_plot <- levels(FullDataset_Object$Celltype_ID_fine)

FullDataset_Object$cellBarcode <- colnames(FullDataset_Object)

cellTypes <- levels(as.factor(FullDataset_Object$Celltype_ID_fine))

cellTypes <- cellTypes[cellTypes %in% celltypes_to_plot]

meta.data.sub <- FullDataset_Object@meta.data[,c("Cohort",
                                                 "disease.ident", # cohort.ident condition
                                                 "Celltype_ID_fine", # cell.type.ident
                                                 "orig.ident", # subject.ident
                                                 "cellBarcode")]



get.CT.DS.subj.vector <- function(cellTypes){
  
  tmp.meta.data <- meta.data.sub %>% dplyr::filter(Celltype_ID_fine == cellTypes)
  
  cohorts <- unique(tmp.meta.data$Cohort)
  
  disease <- unique(tmp.meta.data$disease.ident)
  
  subjects <- unique(tmp.meta.data$orig.ident)
  
  tmp.CT.DS.subj.vector <- vector()
  
  for(j in 1:length(cohorts)){
    
    for(k in 1:length(disease)){
      
      for(l in 1:length(subjects)){
      
      temp.cells <- tmp.meta.data %>% dplyr::filter(Cohort==cohorts[j] & disease.ident==disease[k] & orig.ident==subjects[l]) %>% pull(cellBarcode)
      
      if ( length(temp.cells) >15 ) { # >=
        
        tmp.CT.DS.subj.vector <- c(tmp.CT.DS.subj.vector, paste(cellTypes, cohorts[j], disease[k], subjects[l], sep="__"))
        
        }
      }
      
    }

  }
  
  cat("Completed for ", cellTypes, ".\n", sep="")
  
  return(tmp.CT.DS.subj.vector)
  
}

celltype_cohort_subject.list <- parallel::mclapply(cellTypes, get.CT.DS.subj.vector, mc.cores=1)

celltype_cohort_subject <- unlist(celltype_cohort_subject.list)
celltype_cohort_subject
```
```{r}
library(Matrix)

DefaultAssay(FullDataset_Object) <- "RNA"

get.SubjectcohortCellTypeAvg <- function(celltype_cohort_subject){
  
  temp.cell.type <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][1]
  
  temp.cohort <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][2]
  
  temp.disease <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][3]
  
  temp.subject <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][4]
  
  temp.meta.data <- FullDataset_Object@meta.data[,c("Cohort", "disease.ident", "Celltype_ID_fine", "orig.ident", "cellBarcode")]
  
  temp.cells <- temp.meta.data %>% dplyr::filter(Celltype_ID_fine==temp.cell.type & Cohort==temp.cohort & disease.ident==temp.disease &
                                            
                                            orig.ident==temp.subject) %>% pull(cellBarcode)
  
  if (length(temp.cells) > 15) {
    
    tmp.df <- as.data.frame(rowMeans(GetAssayData(FullDataset_Object)[,temp.cells]))       
    
  } else {
    
    tmp.df <- as.data.frame(GetAssayData(FullDataset_Object)[,temp.cells])
    
    cat("Subject",temp.subject,"only has 1",temp.cell.type,"cell, using singlet for",temp.cohort,"representation...\n",sep=" ")
    
  }
  
  colnames(tmp.df) <- paste(celltype_cohort_subject)
  
  return(tmp.df)
  
}



collapsed.mtx.list <- parallel::mclapply(celltype_cohort_subject, get.SubjectcohortCellTypeAvg, mc.cores=1)

collapsed.SubjectcohortCellTypeAvg.mtx <- Matrix(as.matrix(do.call(cbind, collapsed.mtx.list)), sparse = TRUE)

dim(collapsed.SubjectcohortCellTypeAvg.mtx) # Average for each subject for each gene 

```

```{r}
heatmap_metadata <- as.data.frame(cbind(colnames(collapsed.SubjectcohortCellTypeAvg.mtx),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 1),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 2),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 3),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 4)
                                        )
                                  )


colnames(heatmap_metadata) <- c("cell.ident","cell.type.ident", "cohort.ident", "disease.ident", "subject.ident")


heatmap_metadata$disease.ident %>% unique()
```
```{r}
heatmap_metadata$cell.type.ident <- factor(heatmap_metadata$cell.type.ident, levels=celltypes_to_plot)

heatmap_metadata$cohort.ident <- factor(heatmap_metadata$cohort.ident, levels=c("Germany", "France","Belgium"))

heatmap_metadata$disease.ident <- factor(heatmap_metadata$disease.ident, levels=c( "CTRL", "PPFE", "IPF"))

heatmap_metadata
```
```{r}
cell_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident, disease.ident, subject.ident ) %>% pull(cell.ident)

cohort_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident,  disease.ident, subject.ident ) %>% pull(cohort.ident)

disease_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident, disease.ident, subject.ident ) %>% pull(disease.ident)

celltype_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident,  disease.ident, subject.ident ) %>% pull(cell.type.ident)

subject_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident,  disease.ident, subject.ident ) %>% pull(subject.ident )
```

```{r}
myUnityNormalize <- function(x){(x-min(x))/(max(x)-min(x))}


ppfe_cells <- heatmap_metadata %>% 
    dplyr::filter(cohort.ident %in% c("Germany", "France")) %>% 
    pull(cell.ident)
ipf_cells <- heatmap_metadata %>% dplyr::filter(cohort.ident == "Belgium") %>% pull(cell.ident)

heatmap_df1 <-  as.matrix(collapsed.SubjectcohortCellTypeAvg.mtx[genes_for_heatmap,cell_order])
heatmap_df <- heatmap_df1

heatmap_df_ppfe <- heatmap_df[, ppfe_cells]
heatmap_df_ipf <- heatmap_df[, ipf_cells]

heatmap_df_ppfe_normalized <- t(apply(heatmap_df_ppfe, MARGIN = 1, FUN = myUnityNormalize))
heatmap_df_ipf_normalized <- t(apply(heatmap_df_ipf, MARGIN = 1, FUN = myUnityNormalize))

# Combine both normalized datasets
heatmap_df_normalized <- cbind(heatmap_df_ppfe_normalized, heatmap_df_ipf_normalized)
heatmap_df_normalized <- heatmap_df_normalized[genes_for_heatmap,cell_order]  # Originale Reihenfolge wiederherstellen


library(ComplexHeatmap)
cohort_colors <- palette_scp(x = cohort_order, palcolor = pal_cohort_pal_heat, n = 3, matched = F) # disease.pal
disease_colors <- palette_scp(x = disease_order, palcolor = pal_dis_pal, n = 3, matched = F) # disease.pal
subject_colors <- SCP::palette_scp(x = subject_order,  palcolor = pal_subject_pal, n = 64, matched = F)
celltype_colors <- pal_cluster_scp_pal


# Plot
heatmap_cohort_annotation <- HeatmapAnnotation(cell_type=celltype_order, cohort=cohort_order, disease = disease_order, subject=subject_order,
                                               
                                               col = list(cohort=cohort_colors, disease = disease_colors, cell_type=celltype_colors, subject=subject_colors),
                                               
                                               show_legend = c("subject" = FALSE), 
                                               annotation_label = c("Celltype", "Cohort", "Disease", "Subject")
)
```

```{r, fig.width=12, fig.height=9.5}
library(viridis)
p <- Heatmap(heatmap_df_normalized, name = "Scaled_Expression",
        col = inferno(256), 
        cluster_rows = F, 
        cluster_columns = F, 
        show_column_names = FALSE, 
        top_annotation=heatmap_cohort_annotation, 
        column_split=celltype_order,
        column_title = NULL, 
        use_raster=FALSE,
        column_gap = unit(0.25, "mm"))


# Export as PDF 
pdf(file.path(folder, "Figure_4_Heatmap_Final_narrow.pdf"), width = 7, height = 11)
p
dev.off()
```

#===============

# Marker Genes per Subject
```{r}
# Define Marker Function with Multithreading
myMultithreadFindMarkersDOR <- function(seurat.object, group.name, subject.ident, logFC.min.filter, ncores) {
    library(parallel)
    seurat.object$cellBarcode <- colnames(seurat.object)
    num.cellsTotal <- nrow(seurat.object@meta.data)
    group.levels <- as.vector(unique(seurat.object@meta.data[[group.name]]))
    subject.levels <- as.vector(unique(seurat.object@meta.data[[subject.ident]]))
    
    # Multithread function
    MultithreadFindMarkersDOR <- function(x) {
        temp.cells <- seurat.object@meta.data %>%
            filter(seurat.object@meta.data[[group.name]] == x) %>%
            pull(cellBarcode)
        
        # Calculate per-subject averages for in-group and out-group
        subject.mean.exp <- lapply(subject.levels, function(subj) {
            subj.cells <- seurat.object@meta.data %>%
                filter(seurat.object@meta.data[[subject.ident]] == subj) %>%
                pull(cellBarcode)
            inGroup.cells <- intersect(temp.cells, subj.cells)
            outGroup.cells <- setdiff(subj.cells, temp.cells)
            
            avgExp.inGroup <- if (length(inGroup.cells) > 0) {
                rowMeans(seurat.object@assays$RNA@data[, inGroup.cells, drop = FALSE])
            } else {
                rep(0, nrow(seurat.object@assays$RNA@data))
            }
            
            avgExp.outGroup <- if (length(outGroup.cells) > 0) {
                rowMeans(seurat.object@assays$RNA@data[, outGroup.cells, drop = FALSE])
            } else {
                rep(0, nrow(seurat.object@assays$RNA@data))
            }
            
            list(avgExp.inGroup = avgExp.inGroup, avgExp.outGroup = avgExp.outGroup)
        })
        
        temp.avgExpAllGenes.inGroup <- Reduce("+", lapply(subject.mean.exp, `[[`, "avgExp.inGroup")) / length(subject.levels)
        temp.avgExpAllGenes.outGroup <- Reduce("+", lapply(subject.mean.exp, `[[`, "avgExp.outGroup")) / length(subject.levels)
        
        temp.all.logFC <- temp.avgExpAllGenes.inGroup - temp.avgExpAllGenes.outGroup
        temp.filt.logFC <- temp.all.logFC[temp.all.logFC >= logFC.min.filter]
        temp.numGenesFilt <- length(temp.filt.logFC)
        
        cat("Computing statistics for ", temp.numGenesFilt, " genes for ", x, ".\n", sep = "")
        
        num.cellsInGroup <- length(temp.cells)
        num.cellsOutGroup <- num.cellsTotal - num.cellsInGroup
        
        num.TruePos <- rowSums(seurat.object@assays$RNA@data[names(temp.filt.logFC), temp.cells] > 0)
        num.FalsePos <- rowSums(seurat.object@assays$RNA@data[names(temp.filt.logFC), !colnames(seurat.object@assays$RNA@data) %in% temp.cells] > 0)
        
        num.FalseNeg <- num.cellsInGroup - num.TruePos
        num.TrueNeg <- num.cellsOutGroup - num.FalsePos
        
        temp.logDOR <- log((num.TruePos + 0.5) / (num.FalsePos + 0.5) / ((num.FalseNeg + 0.5) / (num.TrueNeg + 0.5)))
        
        temp.data <- seurat.object@assays$RNA@data[names(temp.filt.logFC), ]
        p_val <- sapply(1:nrow(temp.data), function(x) {
            wilcox.test(x = temp.data[x, temp.cells],
                        y = temp.data[x, seurat.object$cellBarcode[!seurat.object$cellBarcode %in% temp.cells]])$p.value
        })
        names(p_val) <- names(temp.filt.logFC)
        p_val_adj <- p.adjust(p = p_val, method = "bonferroni", n = nrow(seurat.object))
        
        temp.df <- data.frame(
            group.name = rep(x, temp.numGenesFilt),
            gene = names(temp.filt.logFC),
            logFC = temp.filt.logFC,
            logDOR = temp.logDOR,
            pct.1 = num.TruePos / num.cellsInGroup,
            pct.2 = num.FalsePos / num.cellsOutGroup,
            p_val = p_val,
            p_val_adj = p_val_adj,
            nCells.in = num.cellsInGroup,
            nCells.out = num.cellsOutGroup
        )
        colnames(temp.df)[colnames(temp.df) == "group.name"] <- group.name
        
        return(temp.df %>% arrange(desc(logDOR)))
    }
    
    outputList <- parallel::mclapply(group.levels, MultithreadFindMarkersDOR, mc.cores = ncores)
    return(Reduce(rbind, outputList))
}

### Lymphoid-Lineage Celltypes
LYM.markers.DOR_subject <- myMultithreadFindMarkersDOR(
    seurat.object=PPFE_lym,
    subject.ident = "orig.ident_final",
    group.name="Celltype",
    logFC.min.filter=0.25, 
    ncores=1)

writexl::write_xlsx(LYM.markers.DOR_subject, "LYM_MARKERS_FINAL_per_SUBJECT.xlsx")
```

#==================

## Boxplots per Subject

### CXCR4 Average per Subject Plot
```{r, fig.width=5, fig.height=5}
# Initialize an empty list to store results for each cell type
test_clean <- subset(PPFE_lym, disease.ident != "IPF")
test_clean$disease.ident_cohort <- factor(test_clean$disease.ident_cohort, 
                                          levels = c("Germany__CTRL", "France__PPFE", "Germany__PPFE"))
results_list <- list()
celltypes <- test_clean$Celltype %>% levels()
DefaultAssay(test_clean) <- "RNA"


# Loop through each cell type
for (celltype in c("CD4+_TC_effector_memory", "B_Cells_memory", "Treg")) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(test_clean, Celltype == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("CXCR4", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(CXCR4)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


p <- ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  
  labs(
    title = "Average CXCR4 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average CXCR4 Expression per subject"
  ) +
  #theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", 
    comparisons = list(
      c("Germany__CTRL", "Germany__PPFE"), 
      c("Germany__CTRL", "France__PPFE"), 
      c("Germany__PPFE", "France__PPFE")
    ),
    hide.ns = F
  ) +
  theme_scp()

#Export as PDF
pdf(file.path(folder,"PPFE_CTRL_CXCR4_mes_OI.pdf"), width = 5.5, height = 6)
p
dev.off()
```


### CXCL13 Average per Subject Plot
```{r, fig.width=5, fig.height=5}
# Initialize an empty list to store results for each cell type
PPFE_lym$Celltype <- PPFE_lym$Celltype_ID_fine
test_clean <- subset(PPFE_lym, disease.ident != "IPF")
test_clean$disease.ident_cohort <- factor(test_clean$disease.ident_cohort, levels = c("Germany__CTRL", "France__PPFE", "Germany__PPFE"))
results_list <- list()
celltypes <- test_clean$Celltype %>% levels()
DefaultAssay(test_clean) <- "RNA"


# Loop through each cell type
for (celltype in c("CD4+_TC_effector_memory")) {
  # Filter and calculate average expression for the current cell type
  average_expression <- FetchData(
    subset(test_clean, Celltype == celltype & disease.ident_cohort != "IPF__Belgium"),
    vars = c("CXCL13", "orig.ident_final", "disease.ident_cohort")
  ) %>%
    group_by(orig.ident_final, disease.ident_cohort) %>%  # Group by subject and disease
    summarize(
      Average_Expression = mean(CXCL13)  # Calculate mean
    ) %>%
    ungroup() %>%
    mutate(CellType = celltype)  # Add cell type as a new column
  
  # Append the result to the list
  results_list[[celltype]] <- average_expression
}

# Combine all results into a single data frame
final_results <- bind_rows(results_list)


p <- ggplot(final_results, aes(x = disease.ident_cohort, y = Average_Expression, fill = disease.ident_cohort)) +
  geom_boxplot(outlier.shape = NA, alpha = 0.6) +  # Boxplot without outlier points
  #geom_jitter(width = 0.2, size = 2, colour = "black") +  # Data points for each subject
  labs(
    title = "Average CXCL13 Expression per Subject by Condition and Cell Type",
    x = "Condition",
    y = "Average CXCL13 Expression per subject"
  ) +
  #theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "none"
  ) +
  scale_fill_manual(values = c("royalblue", "pink", "red3")) +
  facet_wrap(~CellType) +  # Create separate plots for each cell type
  stat_compare_means(
    method = "wilcox.test", 
    label = "p.signif", label.y = c(0.375, 0.3, 0.325),tip.length = 0.01,
    comparisons = list(
      c("Germany__CTRL", "Germany__PPFE"), 
      c("Germany__CTRL", "France__PPFE"), 
      c("Germany__PPFE", "France__PPFE")
    ),
    hide.ns = F
  ) + ylim(c(0,0.5))+
  theme_scp() 
p


png(file.path(folder,"PPFE_CTRL_CXCL13_OI.png"), width = 10, height = 12, res = 1200, units = "in")
p
dev.off()

pdf(file.path(folder,"PPFE_CTRL_CXCL13_imm_OI.pdf"), width = 2.5, height = 6)
p
dev.off()
```