---
title: "CellChatImmune"
author: "Jannik Ruwisch"
date: "2025-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.width = 14,
                      fig.height = 7,
                      #dpi = 1200,
                      dev = "png",
                      cache = F)
```

# Load libraries
```{r}
library(CellChat)
library(patchwork)
library(tidyseurat)
library(Seurat)
options(stringsAsFactors = FALSE)
```

# Choose Folder
```{r}
folder <-  choose.dir()
```

# Load Cellchat objects
```{r}
CellChatPPFE <- readRDS("./Cellchat_Celltype_09012025_CTRL.rds")
CellChatCTRL <- readRDS("./Cellchat_Celltype_09012025_PPFE.rds")
object.list <- list(PPFE = CellChatPPFE, CTRL = CellChatCTRL)
cellchat <- mergeCellChat(object.list, add.names = names(object.list))
cellchat <- netAnalysis_computeCentrality(cellchat, slot.name = "netP")
cellchat@idents %>% levels() -> celltypes_existing
```

#============

# Lymphoids

## Get Idents of interest
```{r}
celltypes_to_use <- cell_types <- c(
  "Adventitial_Fb",
  "Adventitial_like_Fb",
  "Alveolar_Macrophage",
  "B_Cells_memory", 
  "B_Cells_naive",
  "CD4_TC_Cytotoxic", 
  "CD4_TC_effector", 
  "CD4_TC_naive",
  "CD8_TC_effector_memory", 
  "CD8_TC_resident_memory", 
  "DC1",
  "DC2",
  "EC_aerocyte",
  "EC_arterial",
  "Fibrotic_Macrophage", 
  "gamma_delta_TC",
  "IFNresp_Monocyte_derived_Macrophage",
  "ILC3",
  "LangerhansCells",
  "Macrophage_Cycling",
  "Mast",
  "Monocyte_Classical",
  "Monocyte_derived_Macrophage",
  "Monocyte_nonClassical",
  "Neutro",
  "NKCellsCD16_hi",
  "NKCellsCD16_lo",
  "pDC",
  "Plasma_Cells",
  "Subpleural_Fb", 
  "Treg"
)

lymphocytes <- c(
  "B_Cells_memory",
  "B_Cells_naive",
  "CD4_TC_Cytotoxic",
  "CD4_TC_effector",
  "CD4_TC_naive",
  "CD8_TC_effector_memory",
  "CD8_TC_resident_memory",
  "gamma_delta_TC",
  "ILC3",
  "NKCellsCD16_hi",
  "NKCellsCD16_lo",
  "Treg"
)

myeloid_cells <- c(
  "Alveolar_Macrophage",
  "Fibrotic_Macrophage",
  "IFNresp_Monocyte_derived_Macrophage",
  "Macrophage_Cycling",
  "Monocyte_Classical",
  "Monocyte_derived_Macrophage",
  "Monocyte_nonClassical",
  "Neutro",
  "DC1",
  "DC2",
  "pDC",
  "Mast"
)


celltype_color_vector <- c(
  "Aberrant_Basaloid" = "#ff084a",
  "Adventitial_Fb" = "#6A3D9A",
  "Adventitial_like_Fb" = "#CAB2D6",
  "AEC_intermediate" = "#8B8B60",
  "AEC1" = "#199784",
  "AEC2" = "#7F3C8D",
  "Airway_Fb" = "#1F78B4",
  "Alveolar_Fb" = "#A6CEE3",
  "Alveolar_Macrophage" = "#FF6F00", 
  "B_Cells_memory" = "#FFED6F",
  "B_Cells_naive" = "#D6EBB2",
  "Basal" = "#A5AA99",
  "CD4_TC_Cytotoxic" = "#D9B382",
  "CD4_TC_effector" = "#D9D7C9",
  "CD4_TC_naive" = "#E6F5B7",
  "CD8_TC_effector_memory" = "#D8C965",
  "CD8_TC_resident_memory" = "#C7D98C",
  "Ciliated" = "#8BAC5C",
  "Club" = "#715588",
  "CTHRC1_MyoFb" = "#E31A1C",
  "DC1" = "#94CABB", 
  "DC2" = "#1D5152",
  "EC_aerocyte" = "#8491B4",
  "EC_arterial" = "#F39B7F",
  "EC_general_cap" = "#3C5488",
  "EC_lymphatic" = "#00A087",
  "EC_pulmonary_venous" = "#4DBBD5",
  "EC_systemic_venous" = "#E64B35",
  "Fibrotic_Macrophage" = "#BA4769", 
  "gamma_delta_TC" = "#F9CDE4",
  "Goblet" = "#446293",
  "IFNresp_Monocyte_derived_Macrophage" = "#B7BBC9", 
  "ILC3" = "#88ADCC",
  "LangerhansCells" = "#3F4041", 
  "Macrophage_Cycling" = "#67549A", 
  "Mast" = "#CB1700", 
  "Mesothelium" = "#FDBF6F",
  "Monocyte_Classical" = "#6A7998", 
  "Monocyte_derived_Macrophage" = "#BE777C", 
  "Monocyte_nonClassical" = "#BA7769", 
  "Neutro" = "#217885", 
  "NKCellsCD16_hi" = "#DED7DA",
  "NKCellsCD16_lo" = "#C69FC7",
  "pDC" = "#58644F",
  "Pericytes" = "#33A02C",
  "Plasma_Cells" = "#C2ADC0",
  "Secretory" = "#CC831E",
  "Smooth_Muscle" = "#B2DF8A",
  "Subpleural_Fb" = "#FB9A99",
  "Treg" = "#8DD3C7"
)
```

## Interaction Plots
```{r}
pdf(file.path(output_dir,"Adventitials_Immune_Crosstalk1.pdf"), width = 5, height = 5)
par(mfrow = c(1,1), xpd=TRUE)
  netVisual_circle(object.list[[1]]@net$weight,
                   weight.scale = T, 
                   label.edge= F, 
                   edge.width.max = 7,top = 0.15, 
                   remove.isolate = T, vertex.label.cex = 0.45,arrow.size = 1.25, 
                   sources.use = adventitials,
                   targets.use = c(lymphocytes),
                   color.use = cell_colors,
                   vertex.label.color = "black",  
                   title.name = paste0("Number of interactions - ", names(object.list)[1]))

dev.off()

```

## Pathways Chord Plot
```{r}
pdf(file.path(output_dir,"Adventitials_Immune_Crosstalk2.pdf"), width = 5, height = 5)
par(mfrow = c(1,1), xpd=TRUE)
netVisual_chord_gene(object.list[[1]],
                       sources.use = c("Adventitial_Fb", "Adventitial_like_Fb", "Subpleural_Fb"),
                       targets.use = lymphocytes, slot.name = "netP", 
                       color.use = cell_colors, show.legend = F, 
                        big.gap = 5,thresh = 0.05, small.gap = 3, 
                        lab.cex = 0.5)

dev.off()
```

## CXCL Pathway Chord Plot
```{r}
pdf(file.path(output_dir,"Adventitials_Immune_Crosstalk3.pdf"), width = 5, height = 5)
par(mfrow = c(1,1), xpd=TRUE)
netVisual_chord_gene(object.list[[1]],signaling = "CXCL",
                       sources.use = c("Adventitial_Fb", "Adventitial_like_Fb", "Subpleural_Fb"),
                       targets.use = lymphocytes, 
                       color.use = cell_colors, show.legend = F, 
                        big.gap = 5,thresh = 0.05, small.gap = 3, 
                        lab.cex = 0.5)

dev.off()
```


#============

# Myeloids

## Interaction Plot
```{r}
pHeat <- netVisual_heatmap(cellchat,
                           comparison = c( 2:1), # PPFE vs. CTRL
                           remove.isolate = T,
                           cluster.rows = T, 
                           cluster.cols = T,                                
                           measure = "weight", 
                           targets.use = c("Alveolar_Macrophage", 
                                               "Fibrotic_Macrophage",
                                              "IFNresp_Monocyte_derived_Macrophage", 
                                              "Monocyte_Classical", 
                                              "Monocyte_derived_Macrophage", 
                                              "Monocyte_nonClassical", 
                                              "Neutro",
                                              "DC1", 
                                              "DC2",
                                              "pDC",
                                              "Mast")
                       )                      

# Create a data frame for plotting
legend_df <- data.frame(
  x = seq(1, 100),
  y = 1,
  z = seq(-1, 1, length.out = 100)  # dummy values for gradient
)

# Define custom color gradient
custom_colors <- colorRampPalette(c("#b6222f", "white","#396fb1"))(256) # Max & min Color Hex from Heatmap

# Generate the vertical legend bar
p <- ggplot(legend_df, aes(x = x, y = y, fill = z)) +
  geom_tile() +
  scale_fill_gradientn(
    colors = custom_colors,
    limits = c(-1, 1),
    name = "Color Scale",
    guide = guide_colorbar(
      direction = "vertical",
      title.position = "top",
      barwidth = unit(0.6, "cm"),
      barheight = unit(6, "cm")
    )
  ) +
  theme_void() +
  theme(
    legend.position = "right",
    legend.title = element_text(size = 10, face = "bold")
  )

# Export PDF
pdf("scalebar_myeloid.pdf")
p
dev.off()

pdf(file.path(output_dir,"Relative_Heatmap_To_Myeloids.pdf"), width = 7, height = 10)
pHeat
dev.off()
```
