---
title: "PPPFE_merge_cleaned_data"
author: "Jannik_Ru"
date: "2024-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.width = 10,
                      fig.height = 5,
                      #dpi = 1200,
                      dev = "png",
                      cache = F,
                      fig.path= "/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/")
```

```{r}
# INfos
## Dataset was created with 10X Flex Tech >> Lower UMIs, Features and Counts than Xenium ! 
```

```{r}
library(SCP)
library(Seurat)
Csparse_validate = "CsparseMatrix_validate"
library(SeuratObject)
#library(renv)
#library(SCP)
library(dplyr)
library(tidyverse)
library(tidyseurat)
```

```{r}
PPFE_endo <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/Merge_cleaned_datasets/PPFE_endothelium_cleaned_14_05_2024_ALL.rds")
PPFE_mes <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/Merge_cleaned_datasets/PPFE_mesenchyme_cleaned_28_04_2024.rds")
PPFE_myeloid <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/Merge_cleaned_datasets/PPFE_Myeloids_annotated_clean_30_07_2024.rds")
PPFE_lymph <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/Merge_cleaned_datasets/PPFE_Lymphocytes_annotated_clean_30_07_2024.rds")
PPFE_epi <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/Merge_cleaned_datasets/PPFE_epithelium_cleaned_25_03_2024.rds")
PPFE_epi$Celltype_Coarse <-PPFE_epi$Celltype_ID_coarse
```


```{r, fig.width=35}
CellDimPlot(PPFE_epi, group.by = "Celltype_ID", reduction = "ReUMAPind")  |
  CellDimPlot(PPFE_mes, group.by = "Celltype_ID", reduction = "ReUMAP_07")  |
  CellDimPlot(PPFE_endo, group.by = "Celltype_ID", reduction = "ReUMAP_10")  | 
  CellDimPlot(PPFE_myeloid, group.by = "Celltype_ID", reduction = "ReUMAP_15")  | 
  CellDimPlot(PPFE_lymph, group.by = "Celltype_ID", reduction = "ReUMAP_29" ) 

CellDimPlot(PPFE_epi, group.by = "Celltype_Coarse", reduction = "ReUMAPind")  |
  CellDimPlot(PPFE_mes, group.by = "Celltype_Coarse", reduction = "ReUMAP_07")  |
  CellDimPlot(PPFE_endo, group.by = "Celltype_Coarse", reduction = "ReUMAP_10")  | 
  CellDimPlot(PPFE_myeloid, group.by = "Celltype_Coarse", reduction = "ReUMAP_15")  | 
  CellDimPlot(PPFE_lymph, group.by = "Celltype_Coarse", reduction = "ReUMAP_29" ) 
  
```

## set default RNA assay
```{r}

PPFE_epi$batch <- "Epithelium"
PPFE_mes$batch <- "Mesenchyme"
PPFE_endo$batch <- "Endothelium"
PPFE_myeloid$batch <- "Myeloid"
PPFE_lymph$batch <- "Lymphloid"



rds_list <- merge(x = PPFE_epi, y = c(PPFE_mes, PPFE_endo, PPFE_myeloid, PPFE_lymph))
# Get a List of all samples 
rds_list <- SplitObject(rds_list, split.by = "orig.ident")
```
```{r}
lapply(rds_list, function(x) {
  print(dim(GetAssayData(x, assay = "RNA", slot = "counts")))  # Check dimensions of the RNA assay counts
})
```


# RPCA Integration
# Integration CCA try 2

## Normalize + HVF 
```{r}
rds_list <- lapply(rds_list, function(x) {
  DefaultAssay(x) <- "RNA"
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(x, verbose = FALSE, nfeatures = 2000)
  return(x)
})
```
## Scale and PCA
```{r}
features <- SelectIntegrationFeatures(object.list = rds_list, nfeatures = 2000)

## remove mito genes as integrator
features <- features[-grep("MT-", features)]


rds_list <- lapply(X = rds_list, FUN = function(x) {
    x <- ScaleData(x, features = features, vars.to.regress = c("nCount_RNA"), verbose = FALSE)
    x <- RunPCA(x, features = features, verbose = FALSE)
})
```
```{r}
# find smallest dataset
#min(table(PPFE_metadata$orig.ident))
#103
```

## Find RPCA Anchors
```{r}
anchors <- FindIntegrationAnchors(object.list = rds_list, reduction = "rpca", dims = 1:50)
```
























## RPCA integration
```{r}
# continue from PC RUWISCHJ
anchors <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/PPFE_IPF_FINAL_MERGE/achors_PPFE_IPF_merged_int_PPFEref.rds")

# Try Integration
ppfe_integrated <- IntegrateData(anchorset = anchors, k.weight = 30)

saveRDS(ppfe_integrated, "ppfe_IPF_integrated_all_lineages_18122024.rds")
```

```{r, fig.width=14}
VlnPlot(ppfe_integrated, features = "percent.mt.n", group.by = "orig.ident_final", raster = F)
rm(ppfe_integrate)

ppfe_integrated$orig.ident_final %>% unique()
```


```{r}
ppfe_integrated <- ScaleData(ppfe_integrated, vars.to.regress="percent.mt.n")
ppfe_integrated <- RunPCA(ppfe_integrated, verbose = FALSE)
ppfe_integrated <- RunUMAP(ppfe_integrated, dims = 1:50)
```
```{r}
saveRDS(ppfe_integrated, "PPFE_cleaned_datasetes_ALL_RPCA_integrated_26_08_2024.rds")
```


# create a coarse label 
```{r}
ppfe_integrated$Celltype_ID_final_coarse %>% unique()

ppfe_integrated <- ppfe_integrated %>% 
  mutate(Celltype_ID_final = case_when(Lineage == "Epithelium" ~ Celltype_ID_final_coarse,
                                       Lineage == "Mesenchyme" ~ Celltype_ID_final_coarse,
                                       Lineage == "Endothelium" ~ Celltype_ID_coarse,
                                       Lineage == "Myeloid" ~ Celltype_ID_fine,
                                       Lineage == "Lymphoid" ~ Celltype_ID_fine)
         )

ppfe_integrated$Celltype_ID_final %>% unique()
```

```{r}
ppfe_integrated <- ppfe_integrated %>%
  mutate(Celltype = case_when(Celltype_ID == "AEC2" ~ "AEC2",
                                      Celltype_ID == "AEC1" ~ "AEC1",
                                      Celltype_ID == "Club" ~ "Club",
                                      Celltype_ID == "AEC2_inflamm" ~ "AEC2",
                                      Celltype_ID == "AEC1_CTSE" ~ "AEC1",
                                      Celltype_ID == "Basal" ~ "Basal",
                                      Celltype_ID == "Goblet" ~ "Goblet",
                                      Celltype_ID == "Aberrant_basaloid" ~ "Aberrant_basaloid",
                                      Celltype_ID == "Aberrant_Club" ~ "Club",
                                      Celltype_ID == "Ciliated" ~ "Ciliated",
                                      Celltype_ID == "Pericytes" ~ "Pericytes",
                                      Celltype_ID == "Alveolar_Fb" ~ "Fibroblast",
                                      Celltype_ID == "Alveolar_Fb_inflam" ~ "Fibroblast",
                                      Celltype_ID == "Adventitial_Fb_SFRP2" ~ "Adventitial_Fibroblast",
                                      Celltype_ID == "Subpleural_Fb_HAS1" ~ "Fibroblast",
                                      Celltype_ID == "MyoFb_CTHRC1" ~ "Myofibroblast",
                                      Celltype_ID == "Smooth_Muscle" ~ "SMC",
                                      Celltype_ID == "Fb_LEPR" ~ "Fibroblast",
                                      Celltype_ID == "MyoFb" ~ "Fibroblast",
                                      Celltype_ID == "Alveolar_Fb_CEMIP" ~ "Fibroblast",
                                      Celltype_ID == "Smooth_Muscle_TINAGL" ~ "SMC",
                                      Celltype_ID == "EC_pulmonary_venous" ~ "EC_ven",
                                      Celltype_ID == "EC_arterial" ~ "EC_art",
                                      Celltype_ID == "EC_general_cap" ~ "EC_cap",
                                      Celltype_ID == "EC_aerocyte" ~ "EC_cap",
                                      Celltype_ID == "EC_systemic_venous" ~ "EC_ven",
                                      Celltype_ID == "EC_general_cap_inflam" ~ "EC_cap",
                                      Celltype_ID == "EC_lymphatic" ~ "EC_lymph",
                                      Celltype_ID == "EC_systemic_venous_inflam" ~ "EC_ven",
                                      Celltype_ID == "Alveolar_Macrophage_CHIT1" ~ "AM",
                                      Celltype_ID == "Monocyte_Classical" ~ "cMono",
                                      Celltype_ID == "Alveolar_Macrophage" ~ "AM",
                                      Celltype_ID == "Interstitial_Macrophages_perivascular" ~ "MonoM",
                                      Celltype_ID == "Monocyte_nonClassical" ~ "ncMono",
                                      Celltype_ID == "DC2" ~ "DC2",
                                      Celltype_ID == "Macrophage_Cycling" ~ "AM",
                                      Celltype_ID == "Monocyte_derived_Macrophage_CCL3" ~ "MonoM",
                                      Celltype_ID == "Mast" ~ "Mast",
                                      Celltype_ID == "DC1" ~ "DC1",
                                      Celltype_ID == "CXCL10_Monocyte" ~ "AM",
                                      Celltype_ID == "CD4+_follicular_TC" ~ "CD4+TC",
                                      Celltype_ID == "TH17_effector_TC" ~ "CD4+TC",
                                      Celltype_ID == "CD4+_TC" ~ "CD4+TC",
                                      Celltype_ID == "CD4+_naive_TC" ~ "CD4+TC",
                                      Celltype_ID == "Plasma_cells" ~ "Plasma",
                                      Celltype_ID == "Treg" ~ "Treg",
                                      Celltype_ID == "CD8+_tissue_res_TC" ~ "CD8+TC",
                                      Celltype_ID == "CD16+_NK_cells" ~ "NK",
                                      Celltype_ID == "CD8+_effector_TC" ~ "CD8+TC",
                                      Celltype_ID == "B_cells_follicular" ~ "BC",
                                      Celltype_ID == "ILC3" ~ "ILC",
                                      Celltype_ID == "Gamma_delta_TC" ~ "GDTC",
                                      Celltype_ID == "B_cells_naive" ~ "BC",
                                      Celltype_ID == "B_cells_memory" ~ "BC",
                                      Celltype_ID == "CD16-_NK_cells" ~ "NK",
                                      Celltype_ID == "Neuroendocrine" ~ "NEC",
                                      Celltype_ID == "pDC" ~ "pDC",
                                      Celltype_ID == "Neutrophils" ~ "Neutro",
                                      Celltype_ID == "Basal_Club_Transitional" ~ "Basal",
                                      Celltype_ID == "Mesothelium" ~ "Meso",
                                      Celltype_ID == "B_cells_transitional" ~ "BC"),
         lineage = batch)

```

# optimize embedding
```{r}
ppfe_integrated <- RunUMAP2(object = ppfe_integrated, dims = 1:15, reduction = "pca", reduction.name = "ReUMAP_15", 
                            reduction.key = "ReUMAP_15")
```

```{r}
#CellDimPlot(ppfe_integrated, group.by = "Celltype", raster = F, label = T, label_insitu = T, label_repel = T, legend.position = "none", reduction = "ReUMAP_30")
CellDimPlot(ppfe_integrated, group.by = "Celltype", raster = F, label = T, label_insitu = T, label_repel = T, legend.position = "none", reduction = "umap", palette = "Dark2", pt.size = 0.5)

```
```{r}
p <- CellDimPlot(ppfe_integrated, group.by = "Celltype", raster = F, pt.size = 0.15, reduction = "umap", palette = "Paired", show_stat = F, xlab = "UMAP_1", ylab = "UAMP_2", legend.position = "none")+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank())  # Remove axis ticks

pdf("PPFE_MES_UMAP.pdf", height = 14, width = 14)
p
dev.off()
p
```

```{r}
p <- CellDimPlot(ppfe_integrated, group.by = "lineage", raster = F, pt.size = 0.15, reduction = "umap", palette = "Dark2", show_stat = F, xlab = "UMAP_1", ylab = "UAMP_2", legend.position = "none")+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank())  # Remove axis ticks

pdf("PPFE_MES_UMAP_Lineage.pdf", height = 14, width = 14)
p
dev.off()
p
```

### 6A) Celltype_ID
```{r}
ppfe_integrated$lineage <- factor(ppfe_integrated$lineage)
```

```{r}
test <- SCP::palette_scp(x = levels(ppfe_integrated$lineage), n = length(levels(ppfe_integrated$lineage)),
                         palette = "Dark2", matched = T)

# Proportion / cell number composition per cluster
ggData = data.frame(prop.table(table(ppfe_integrated$lineage, ppfe_integrated$orig.ident), margin = 2))
colnames(ggData) = c("Celltype_ID", "Orig.Ident", "value")

ggData <- ggData %>%
  mutate(Disease = substr(Orig.Ident, 1,4))

ppfe_integrated$lineage %>% unique() -> 
  Celltypes
levels(Celltypes)
cluster_scp_pal <- SCP::palette_scp(x = levels(Celltypes))

patient_order <- ggData %>%
  dplyr::filter(Celltype_ID == 'Lymphloid') %>%
  arrange(desc(value)) %>%
  pull(Orig.Ident)

# Convert Patient_ID to a factor with the specific order
ggData$Orig.Ident <- factor(ggData$Orig.Ident, levels = patient_order)


# Calculate median values for each Celltype_ID within each Disease group
medians <- ggData %>%
  dplyr::filter(Disease =="PPFE") %>%
  group_by(Disease, Celltype_ID) %>%
  summarize(median_value = median(value)) %>%
  ungroup()

# Order Celltype_ID based on median values
ordered_celltypes <- medians %>%
  group_by(Celltype_ID) %>%
  summarize(overall_median = median(median_value)) %>%
  arrange(overall_median) %>%
  pull(Celltype_ID)

ordered_celltypes %>% levels()

cell_types <- c("Epithelium" , "Mesenchyme" , "Endothelium" , "Myeloid" , "Lymphloid" )

# Invert the order of the cell types
inverted_cell_types <- rev(cell_types)

# Update the levels of Celltype_ID in ggData
ggData$Celltype_ID <- factor(ggData$Celltype_ID, levels = inverted_cell_types)

ggData$Celltype_ID

p <- ggplot(ggData, aes(x = Orig.Ident, y = value, fill = Celltype_ID)) +
  geom_bar(stat = "identity", position = "stack", size = 0.5, color = "black") +
  labs(title = "Relative cell frequencies by subject",
       x = "Patient ID",
       y = "Frequency (%)") + 
  #scale_fill_discrete(cluster_scp_pal) +
  #scale_color_discrete(cluster_scp_pal) +
  scale_fill_manual(values = test) +
  scale_color_manual(values = test) +
  theme_scp() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~Disease, scales = "free_x")

pdf("PPFE_mes_stacked_bar_plots_by_subject.pdf", width = 12, height = 7)
p
dev.off()
p
```

```{r, fig.width=14}
library(ggpubr)
# Convert disease.ident and Celltype to factors
ggData$Disease <- as.factor(ggData$Disease)
ggData$Celltype_ID <- as.factor(ggData$Celltype)

# Calculate the median frequency for each cell type
median_frequencies <- ggData %>%
  group_by(Celltype_ID) %>%
  summarize(median_freq = median(value)) %>%
  arrange(-median_freq)

# Reorder the Celltype factor levels based on median frequency
ggData$Celltype_ID <- factor(ggData$Celltype_ID, levels = median_frequencies$Celltype_ID)

# Plot
p <- ggplot(ggData, aes(x = Celltype_ID, y = value, fill = Disease)) +
  geom_boxplot(outlier.shape = "") +
  labs(title = "Comparison of Cell Type Frequencies Between Disease Groups",
       x = "Cell Type",
       y = "Frequency (%)") +
  scale_fill_manual(values = c("royalblue", "red3")) +
  scale_color_manual(values = c("royalblue", "red3")) +
  theme_scp() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Add statistical comparisons
p <- p + stat_compare_means(aes(group = Disease), #method = "t.test", 
                            label = "p.signif")

# Display the plot
print(p)

pdf(file = "PPFE_ALL_Cellfreqencies.pdf", width = 10, height = 7)
p
dev.off()
```




```{r}
SCP::palette_scp(palette = "Set1", n = length(ppfe_integrated$orig.ident %>% unique()), matched = F) -> palette

p <- DimPlot(ppfe_integrated, group.by = c("orig.ident"),shuffle = T, raster = F, label = F, combine = T, reduction = "umap")+
  theme_scp()+NoLegend()+ggtitle("Subject")+
  scale_color_manual(values = as.vector(palette))|
  DimPlot(ppfe_integrated, group.by = c("disease.ident"),shuffle = T, raster = F, label = F, combine = T, reduction = "umap", cols = c("royalblue", "red3"))+
  theme_scp()+NoLegend()+ggtitle("Disease")

pdf(file = "PPFE_ALL_subject_Disease_UMAP.pdf", width = 14, height = 7)
p
dev.off()
```
# Final Save
```{r}
saveRDS(ppfe_integrated, "PPFE_cleaned_datasetes_ALL_RPCA_integrated_12_09_2024.rds")
```