---
title: "PPFE_Downstream"
author: "Jannik"
date: "2024-14-03"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      fig.width = 10,
                      fig.height = 5,
                      #dpi = 1200,
                      dev = "png",
                      cache = F,
                      fig.path= "/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/")
```

```{r}
# INfos
## Dataset was created with 10X Flex Tech >> Lower UMIs, Features and Counts than Xenium ! 
```

```{r}
library(SCP)
library(Seurat)
Csparse_validate = "CsparseMatrix_validate"
library(SeuratObject)
#library(renv)
#library(SCP)
library(dplyr)
library(tidyverse)
library(tidyseurat)
```



# Load_Dataset
```{r}
ppfe <- readRDS("/mnt/dzl_bioinf/ruwischj/scRNA_Seq/PPFE_Nuclei_Seq/Merged_Dataset_B1_B2_ppfe.rpca.integrated_RPCA_cleaned_07_10_2024.rds")

```


# Adjust Metadata
```{r}
# Adjust Disease.idnetz

ppfe <- ppfe %>% 
  dplyr::mutate(disease.ident = case_when(disease.ident == "PPF" ~ "PPFE", .default = "CTRL"))
```


```{r}
library(stringr)
# Add Cohort ID and Batch ID 
Batch2_IDs <- c( "PPFE_PPFE21", 
 "PPFE_PPFE22", 
 "PPFE_PPFE25", 
 "PPFE_PPFE26", 
 "PPFE_PPFE27", 
 "PPFE_PPFE28", 
 "PPFE_PPFE29", 
 "PPFE_PPFE30", 
 "PPFE_PPFE31", 
 "PPFE_PPFE32", 
 "PPFE_PPFE33", 
 "PPFE_PPFE34", 
 "PPFE_PPFE35", 
 "PPFE_PPFE37", 
 "PPFE_PPFE38", 
 "PPFE_PPFE40", 
 "CTRL_CTR056", 
 "CTRL_CTR058", 
 "PPFE_PPFE23", 
 "PPFE_PPFE24", 
 "PPFE_PPFE36", 
 "PPFE_PPFE39", 
 "PPFE_PPFE41", 
 "PPFE_PPFE42", 
 "PPFE_PPFE43", 
 "PPFE_PPFE44")

Batch2_Fren_IDs <- c("PPFE_PPFE21", 
 "PPFE_PPFE22", 
 "PPFE_PPFE25", 
 "PPFE_PPFE26", 
 "PPFE_PPFE27", 
 "PPFE_PPFE28", 
 "PPFE_PPFE29", 
 "PPFE_PPFE30", 
 "PPFE_PPFE31", 
 "PPFE_PPFE32", 
 "PPFE_PPFE33", 
 "PPFE_PPFE34", 
 "PPFE_PPFE35", 
 "PPFE_PPFE37", 
 "PPFE_PPFE38", 
 "PPFE_PPFE40", 
 "PPFE_PPFE23", 
 "PPFE_PPFE24", 
 "PPFE_PPFE36", 
 "PPFE_PPFE39")
```


```{r}
Batch2_Han_IDs <- c("PPFE_PPFE40", 
                    "PPFE_PPFE41", 
                    "PPFE_PPFE42",
                    "PPFE_PPFE43",
                    "PPFE_PPFE44",
                    "CTRL_CTR056", # CAVE Bad Mapping QC !
                    "CTRL_CTR058")
```


```{r}
ppfe <- ppfe %>%
  mutate(Cohort = case_when(orig.ident %in% Batch2_Fren_IDs ~ "France",
                            .default = "Germany")
         )

table(ppfe$orig.ident, ppfe$Cohort)
```




# 1. CellDimplot
```{r}
CellDimPlot(ppfe, group.by = "Seuratcorrected_snn_res.0.2", raster = F, label = T, label_insitu = T, reduction = "umap")
CellDimPlot(ppfe, group.by = "Seuratcorrected_snn_res.1", raster = F, label = T, label_insitu = T, reduction = "umap")
```


```{r}
CellDimPlot(ppfe, group.by = "Seuratcorrected_snn_res.1", raster = F, label = T, reduction = "umap")
CellDimPlot(ppfe, group.by = "orig.ident", raster = F, reduction = "umap")
DimPlot(ppfe, group.by = "disease.ident", raster = F, shuffle = T, raster.dpi = c(600, 600), reduction = "umap")
CellDimPlot(ppfe, group.by = "Seuratcorrected_snn_res.0.2", raster = F, label = T, split.by = "disease.ident", reduction = "umap")


```
```{r, fig.width=9, fig.height=9}
DimPlot(ppfe, group.by = "disease.ident", raster = F, shuffle = T, raster.dpi = c(900, 900), reduction = "umap")
```

# 2. DEGs
```{r}
Markers_0.2 <- FindAllMarkers(ppfe, group.by = "Seuratcorrected_snn_res.0.2", assay = "RNA", logfc.threshold = 1, only.pos = T)

ppfe <- RunDEtest(srt = ppfe, group_by = "integrated_snn_res.0.2", fc.threshold = 1.5, only.pos = T, assay = "RNA")
ppfe <- RunDEtest(srt = ppfe, group_by = "integrated_snn_res.1", fc.threshold = 1.5, only.pos = T, assay = "RNA")

```

### snn_0.2_res
```{r}

#DEGs <- ppfe@tools$DEtest_integrated_snn_res.0.2$AllMarkers_wilcox
DEGs <- Markers_0.2
```
```{r}
DEGs <- DEGs[with(DEGs, avg_log2FC > 0.3 & p_val_adj < 0.05), ] # Filtering all > 0.3 for FOR Dixit Jonas aus Sci Adv Paper

DEGs <- DEGs %>%
  group_by(cluster) %>%
  slice_max(n = 300, order_by = avg_log2FC)

DEGs
```

```{r}
library(dplyr)
DEGs <- DEGs %>% 
  mutate(Celltype_ID = case_when(cluster == 0 ~ "Fibroblasts",
                                cluster == 1 ~ "CD4+TC",
                                cluster == 2 ~ "CD8+TC",
                                cluster == 3 ~ "AEC2",
                                cluster == 4 ~ "AEC1",
                                cluster == 5 ~ "Macrophages",
                                cluster == 6 ~ "EC",
                                cluster == 7 ~ "BC",
                                cluster == 8 ~ "Macrophages",
                                cluster == 9 ~ "SMC",
                                cluster == 10 ~ "PC",
                                cluster == 11 ~ "EC",
                                cluster == 12 ~ "EC",
                                cluster == 13 ~ "Mast",
                                cluster == 14 ~ "Ciliated",
                                cluster == 15 ~ "Club",
                                cluster == 16 ~ "Lymphatics",
                                cluster == 17 ~ "Basal",
                                cluster == 18 ~ "Neutros",
                                cluster == 19 ~ "Cycling_Immune",
                                cluster == 20 ~ "Immune_Dbl",
                                cluster == 21 ~ "AE_Endo_Dbl",
                                cluster == 22 ~ "Mast_AE_Dbl")
         )

DEGs
```


```{r}
# save
writexl::write_xlsx(DEGs, "DEGs_top300_annotated_ppfe_final_RPCA_int_SNN_0.2_Annoated.xlsx")
```

```{r}
ppfe <- AnnotateFeatures(ppfe, species = "Homo_sapiens", db = c("Chromosome", "GeneType", "Enzyme", "TF", "SP"))

feature_annotation <- ppfe[["RNA"]]@meta.features
feature_annotation$gene <- rownames(feature_annotation)


DEGs <-  merge(DEGs, feature_annotation, by = "gene")

#BiocManager::install("fgsea")
library(msigdbr)
library(fgsea)
library(tidyverse)
library(clusterProfiler)
library(ensembldb)
library(biomaRt)

#Adding gene annotations
ensembl_data <- getBM(attributes = c("ensembl_gene_id", "external_gene_name", "entrezgene_id", "description"), mart = useDataset(("hsapiens_gene_ensembl"), useMart("ensembl")))
#ensembl = sanger gene library, "hspaiens -> selecting species database #Merging bot tables an including the "Entrezgene" annotation in the genelist                
DEGs <- merge(DEGs, ensembl_data[,c(2,3,4)], by.x = "gene", 
                                      by.y = "external_gene_name")
# Rm dublicates
DEGs <- DEGs %>% distinct()


# Reorder
DEGs <- DEGs %>%
  group_by(group1) %>%
  slice_max(n = 300, order_by = avg_log2FC)


# print
DEGs

# save
writexl::write_xlsx(DEGs, "DEGs_top300_annotated_ppfe_final_RPCA_int_SNN_0.2.xlsx")
```



## Check marker Expression

### CD4 & CD8
```{r}
FeatureDimPlot(ppfe, features = c( "IL32", 
 "CD3E", 
 "CD3D", 
 "CD2", 
 "CD4",
 "LTB", 
 #"ACAP1", 
 "TRAC", 
 "TRBC2"),
 ncol = 4,
 raster = F,
 assay = "RNA", 
 reduction = "umap")


FeatureDimPlot(ppfe, features = c( "CCL5", 
 "IL32", 
 "CD3D", 
 "NKG7", 
 "CD2", 
 "GZMB", 
 "CTSW", 
 "CST7", 
 "GZMA", 
 "CD7"),
 ncol = 4,
 raster = F,
 assay = "RNA",
 reduction = "umap")
```

### Bcells
```{r}
FeatureDimPlot(ppfe, features = c( "MS4A1", 
 "CD79A", 
 "BANK1", 
 "LTB", 
 "IGKC", 
 "MEF2C", 
 "BIRC3", 
 "STK17A", 
 "LIMD2", 
 "GPR183"),
 ncol = 4,
 raster = F,
 assay = "RNA",
 reduction = "umap")


```


### Endothelial markers
```{r}
FeatureDimPlot(ppfe, features = c("COL15A1", "VWF", "PLVAP", 
                                 "DKK2", "IGFBP3", "SEMA3G",
                                 "PRX", "FCN3", "AFF3"),
 ncol = 3,
 raster = F,
 assay = "RNA",
 reduction = "umap")
```
```{r}
ppfe$Seuratcorrected_snn_res.0.2 %>% unique()
```

# 3.  Rename Cluster Identities
```{r}
#Change ident
Idents(ppfe) <- "Seuratcorrected_snn_res.0.2"


ppfe <- SCP::RenameClusters(ppfe, group.by = "Seuratcorrected_snn_res.0.2", name = "Celltype_ID",
                            nameslist = c(
                              "Fibroblasts", # 0
                               "CD4_TC",  #1
                               "PC", #10
                               "EC", #11
                               "EC", #12 
                               "Mast", #13
                               "Ciliated", #14 
                               "Club", #15
                               "Lymphatic_EC", #16
                               "Basal", #17
                               "Neutros", #18
                              "Cycling_Immune", # 19
                             "CD8_TC", # 2
                              "Immune_Dbl", # 20
                              "AE_Endo_Dbl", # 21
                              "Mast_AE_Dbl", #22 
                               "AEC2", #3
                               "AEC1", #4
                               "Macrophages", # 5
                               "EC", #6
                               "BC", # 7
                               "Macrophages", #8
                               "SMC") #9 
                            )
```

```{r}
ppfe$disease.ident <- factor(ppfe$disease.ident, levels = c("PPFE", "CTRL"))
```

```{r}
#Change ident
Idents(ppfe) <- "Seuratcorrected_snn_res.0.2"


ppfe <- SCP::RenameClusters(ppfe, group.by = "Seuratcorrected_snn_res.0.2", name = "Lineage",
                            nameslist = c(
                              "Stroma", # 0
                               "Immune",  #1
                               "Immune", #10
                               "Endothelium", #11
                               "Endothelium", #12 
                               "Immune", #13
                               "Epithelium", #14 
                               "Epithelium", #15
                               "Endothelium", #16
                               "Epithelium", #17
                               "Immune", #18
                              "Immune", # 19
                             "Immune", # 2
                              "Immune", # 20
                              "Epithelium", # 21
                              "Immune", #22 
                               "Epithelium", #3
                               "Epithelium", #4
                               "Immune", # 5
                               "Endothelium", #6
                               "Immune", # 7
                               "Immune", #8
                               "Stroma") #9 
                            )
```

```{r, fig.height=8, fig.width=16}
#Plot with new ident
CellDimPlot(ppfe, group.by = "Celltype_ID", pt.size = 0.25, label = T, label_insitu = T, raster = F, label_repel = T, label_repulsion = 40, legend.position = "bottom", legend.direction = "horizontal", reduction = "umap")

CellDimPlot(ppfe, group.by = "Lineage", pt.size = 0.25, label = T, label_insitu = T, raster = F, label_repel = T, label_repulsion = 40, legend.position = "bottom", legend.direction = "horizontal", reduction = "umap", palette = "Dark2")
```

## Annotated Dimplots
```{r, fig.height= 25, fig.width=18}
CellDimPlot(ppfe, group.by = "Celltype_ID", pt.size = 0.1, label = T, label_insitu = T, raster = F, label_repel = T, label_repulsion = 40, split.by = "disease.ident", nrow = 2, reduction = "umap")

```

```{r, fig.width=7}
CellDimPlot(ppfe, group.by = "disease.ident", raster = F, palcolor = c("red3", "royalblue"), pt.size = 0.001, reduction = "umap")
```


```{r, fig.width=14, fig.height=14}
DimPlot(ppfe, group.by = "disease.ident", raster = F,cols = c("red3", "royalblue"), pt.size = 0.1, shuffle = T, reduction = "umap")
```

# 4. Cell Counts
```{r}
library(dittoSeq)
library(RColorBrewer)
library(ggpubr)
Paired_pal <- brewer.pal(10, "Paired")
Paired_pal_1 <- c(Paired_pal[1], Paired_pal[6])
dis_pal <- list("red3", "royalblue")
```

```{r, fig.height=15}
dittoFreqPlot(ppfe, "Celltype_ID", sample.by = "orig.ident", group.by = "disease.ident", scale = "percent", split.adjust = list(scales = "free"), 
              do.raster = T,
              raster.dpi = 300,
              boxplot.color = "black",
              boxplot.lineweight = 0.5,
              jitter.size = 2,
              jitter.width = 0.2,
              jitter.color = "black",
              color.panel = list("red3", "royalblue"),
              colors = seq_along(list("red3", "royalblue")),
              
  )+ stat_compare_means(label.x.npc = "left", 
                       #label.y.npc = "bottom",
                       #position = "jitter",
                       #label = "p.signif",
                       #symnum.args = <- list(cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, Inf), symbols = c("****", "***", "**", "*", "ns"))
                       )

```

```{r, fig.width=5}
CellStatPlot(ppfe, stat.by = "Celltype_ID", group.by = "disease.ident", plot_type = "bar")
```


```{r}
CellStatPlot(ppfe, stat.by = "disease.ident", group.by = "Celltype_ID", plot_type = "bar", palcolor = dis_pal)
```


# 5. Heatmap of Markers



##Unity_normalized Markers
```{r, fig.height= 10, fig.width=14}
DEGs %>%
    group_by(Celltype_ID) %>%
    top_n(n = 10, wt = avg_log2FC) -> DEGs_byID_top10.markers

DEGs_byID_top10.markers <- DEGs_byID_top10.markers %>% distinct()

DEGs_byID_top10.markers <- subset(DEGs_byID_top10.markers, 
                                  cluster != 22 &
                                    cluster != 21 &
                                    cluster!= 20)

DEGs_byID_top10.markers

write_xlsx(DEGs_byID_top10.markers, "genes4heatmap_ppfe_all.xslx")
```



```{r, fig.height=17}
pal <- palette_scp(n = 21)
dis_pal <- c("red3", "royalblue")

library(viridis)
library(RColorBrewer)
dittoHeatmap(ppfe, unique(DEGs_byID_top10.markers$gene),
    annot.by = c("Celltype_ID_Coarse", "disease.ident"),
    scaled.to.max = T,
    show_colnames = FALSE,
    show_rownames = TRUE,
    heatmap.colors.max.scaled = viridis_pal(option = "C")(256),
    scale = "row",
    cluster_rows = F,
    annot.colors = c(pal, dis_pal),
    complex = T,
    assay = "RNA"
    )
```
## Dotplot_Markers
```{r,fig.width=11, fig.height=23}
library(SCP)
ht <- GroupHeatmap(
  srt = ppfe,
  features =  DEGs_byID_top10.markers$gene,
  group.by = c("Celltype_ID_Coarse", "disease.ident"),
  heatmap_palette = "RdBu",
  #cell_annotation = c("Roe_stad", "disease_activity"),
  cell_annotation_palette = c("Paired", "Paired", "Paired", "Paired", "Paired", "Paired", "Paired"),
  cell_split_palette = "Paired",
  feature_split_palette = "Paired",
  show_row_names = TRUE, row_names_side = "left",
  add_dot = TRUE, add_reticle = TRUE,
  feature_split = DEGs_byID_top10.markers$Celltype_ID_Coarse,
  cluster_rows = TRUE,
  cluster_columns = F,
  feature_annotation = c("TF", "SP"),
  feature_annotation_palcolor = list(c("gold", "steelblue"), c("forestgreen")),
  height = 30,
  width = 5,
  assay = "RNA"
)

print(ht$plot)
```
## UnityHeatmap
```{r}
library(tidyseurat)
myUnityNormalize <- function(x){(x-min(x))/(max(x)-min(x))}

DEGs_byID_top10.markers <- DEGs_byID_top10.markers %>%
  mutate(Celltype_ID = factor(Celltype_ID, levels = c(
    "AEC1", "AEC2", "Club","Basal","Ciliated", 
    "Fibroblasts","SMC",
    "EC","Lymphatics",
    "Macrophages", "Neutros","Mast","CD4+TC", "CD8+TC", "BC",  "PC", "Cycling_Immune"))) %>%
  arrange(Celltype_ID)

DEGs_byID_top10.markers$Celltype_ID %>% unique()

# Heatmap Genes
genes_for_heatmap <- DEGs_byID_top10.markers$gene
```


```{r}
ppfe$Celltype_ID <- factor(ppfe$Celltype_ID, levels = c(
    "AEC1", "AEC2", "Club","Basal","Ciliated", 
    "Fibroblasts","SMC",
    "EC","Lymphatic_EC",
    "Macrophages", "Neutros","Mast","CD4_TC", "CD8_TC", "BC",  "PC", "Cycling_Immune",
                                            "Mast_AE_Dbl", "AE_Endo_Dbl", "Immune_Dbl")
                           )

celltypes_to_plot <- ppfe$Celltype_ID %>% unique()
celltypes_to_plot %>% levels()
```


```{r}
CellDimPlot(ppfe, group.by = "Celltype_ID", raster = F, label = T, label_insitu = T, label_repel = T, reduction = "umap")
table(ppfe$orig.ident, ppfe$Cohort)
```

```{r}
### with multithreading, first make all possible combinations
FullDataset_Object <- ppfe

celltypes_to_plot <- levels(FullDataset_Object$Celltype_ID)

FullDataset_Object$cellBarcode <- colnames(FullDataset_Object)

cellTypes <- levels(as.factor(FullDataset_Object$Celltype_ID))

cellTypes <- cellTypes[cellTypes %in% celltypes_to_plot]

meta.data.sub <- FullDataset_Object@meta.data[,c("Cohort",
                                                 "disease.ident", # cohort.ident condition
                                                 "Celltype_ID", # cell.type.ident
                                                 "orig.ident", # subject.ident
                                                 "cellBarcode")]



get.CT.DS.subj.vector <- function(cellTypes){
  
  tmp.meta.data <- meta.data.sub %>% dplyr::filter(Celltype_ID == cellTypes)
  
  cohorts <- unique(tmp.meta.data$Cohort)
  
  disease <- unique(tmp.meta.data$disease.ident)
  
  subjects <- unique(tmp.meta.data$orig.ident)
  
  tmp.CT.DS.subj.vector <- vector()
  
  for(j in 1:length(cohorts)){
    
    for(k in 1:length(disease)){
      
      for(l in 1:length(subjects)){
      
      temp.cells <- tmp.meta.data %>% dplyr::filter(Cohort==cohorts[j] & disease.ident==disease[k] & orig.ident==subjects[l]) %>% pull(cellBarcode)
      
      if ( length(temp.cells) >3 ) { # >=
        
        tmp.CT.DS.subj.vector <- c(tmp.CT.DS.subj.vector, paste(cellTypes, cohorts[j], disease[k], subjects[l], sep="__"))
        
        }
      }
      
    }

  }
  
  cat("Completed for ", cellTypes, ".\n", sep="")
  
  return(tmp.CT.DS.subj.vector)
  
}

celltype_cohort_subject.list <- parallel::mclapply(cellTypes, get.CT.DS.subj.vector, mc.cores=8)

celltype_cohort_subject <- unlist(celltype_cohort_subject.list)
celltype_cohort_subject
```
```{r}
library(Matrix)

DefaultAssay(FullDataset_Object) <- "RNA"

get.SubjectcohortCellTypeAvg <- function(celltype_cohort_subject){
  
  temp.cell.type <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][1]
  
  temp.cohort <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][2]
  
  temp.disease <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][3]
  
  temp.subject <- strsplit(as.character(celltype_cohort_subject),"__")[[1]][4]
  
  temp.meta.data <- FullDataset_Object@meta.data[,c("Cohort", "disease.ident", "Celltype_ID", "orig.ident", "cellBarcode")]
  
  temp.cells <- temp.meta.data %>% dplyr::filter(Celltype_ID==temp.cell.type & Cohort==temp.cohort & disease.ident==temp.disease &
                                            
                                            orig.ident==temp.subject) %>% pull(cellBarcode)
  
  if (length(temp.cells) > 3) {
    
    tmp.df <- as.data.frame(rowMeans(GetAssayData(FullDataset_Object)[,temp.cells]))       
    
  } else {
    
    tmp.df <- as.data.frame(GetAssayData(FullDataset_Object)[,temp.cells])
    
    cat("Subject",temp.subject,"only has 1",temp.cell.type,"cell, using singlet for",temp.cohort,"representation...\n",sep=" ")
    
  }
  
  colnames(tmp.df) <- paste(celltype_cohort_subject)
  
  return(tmp.df)
  
}



collapsed.mtx.list <- parallel::mclapply(celltype_cohort_subject, get.SubjectcohortCellTypeAvg, mc.cores=8)

collapsed.SubjectcohortCellTypeAvg.mtx <- Matrix(as.matrix(do.call(cbind, collapsed.mtx.list)), sparse = TRUE)

dim(collapsed.SubjectcohortCellTypeAvg.mtx) # Average for each subject for each gene 

```
```{r}
heatmap_metadata <- as.data.frame(cbind(colnames(collapsed.SubjectcohortCellTypeAvg.mtx),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 1),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 2),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 3),
                                        
                                        sapply(strsplit(as.character(colnames(collapsed.SubjectcohortCellTypeAvg.mtx)),"__"), `[`, 4)
                                        )
                                  )


colnames(heatmap_metadata) <- c("cell.ident","cell.type.ident", "cohort.ident", "disease.ident", "subject.ident")


heatmap_metadata
```
```{r}
heatmap_metadata$cell.type.ident <- factor(heatmap_metadata$cell.type.ident, levels=celltypes_to_plot)

heatmap_metadata$cohort.ident <- factor(heatmap_metadata$cohort.ident, levels=c("Germany","France"))

heatmap_metadata$disease.ident <- factor(heatmap_metadata$disease.ident, levels=c("PPFE","CTRL"))

heatmap_metadata
```
```{r}
cell_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident, disease.ident, subject.ident ) %>% pull(cell.ident)

cohort_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident,  disease.ident, subject.ident ) %>% pull(cohort.ident)

disease_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident, disease.ident, subject.ident ) %>% pull(disease.ident)

celltype_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident,  disease.ident, subject.ident ) %>% pull(cell.type.ident)

subject_order <- heatmap_metadata %>% arrange(cell.type.ident, cohort.ident,  disease.ident, subject.ident ) %>% pull(subject.ident )
```

```{r}
heatmap_df1 <-  as.matrix(collapsed.SubjectcohortCellTypeAvg.mtx[genes_for_heatmap,cell_order])

lineage_for_heatmap <- c("FXYD3", "EPCAM", "ELF3", # Epi
                         "COL1A2", "DCN", "MFAP4", # Stroma
                         "CLDN5", "ECSCR", "CLEC14A", # Endo
                          "CD53", "PTPRC", "CORO1A") # Immune

heatmap_df2 <- as.matrix(collapsed.SubjectcohortCellTypeAvg.mtx[lineage_for_heatmap,cell_order])

separation_row <- matrix(NA, nrow = 1, ncol = ncol(heatmap_df2))

#heatmap_df <- heatmap_df1
heatmap_df <- rbind(heatmap_df2, heatmap_df1)



heatmap_df_normalized <- t(apply(heatmap_df, MARGIN=1, FUN=myUnityNormalize))


library(ComplexHeatmap)
dis_pal <- list("red3", "royalblue")
cohort_pal <- list("darkgrey", "lightgrey")

cohort_colors <- palette_scp(x = cohort_order, palcolor = cohort_pal, n = 2, matched = F) # disease.pal
disease_colors <- palette_scp(x = disease_order, palcolor = dis_pal, n = 2, matched = F) # disease.pal
celltype_colors <- palette_scp(x = celltype_order, palette = "Paired", n = 18, matched = F)
subject_colors <- SCP::palette_scp(x = subject_order, palette = "Dark2", n = 28, matched = F)

heatmap_cohort_annotation <- HeatmapAnnotation(cell_type=celltype_order, cohort=cohort_order, disease = disease_order, subject=subject_order,
                                               
                                               col = list(cohort=cohort_colors, disease = disease_colors, cell_type=celltype_colors, subject=subject_colors),
                                               
                                               show_legend = c("subject" = FALSE))
```

```{r, fig.width=14, fig.height=23}
library(viridis)
p <- Heatmap(heatmap_df_normalized, 
        col = inferno(256), 
        cluster_rows = F, 
        cluster_columns = F, 
        show_column_names = FALSE, 
        top_annotation=heatmap_cohort_annotation, 
        column_split=celltype_order, 
        row_split = c(rep("1. Lineage Markres", nrow(heatmap_df2)), rep("2. Celltype Marker", nrow(heatmap_df1))),  # split to create visual separation
        row_gap = unit(c(2, 2), "mm"),  # larger gap around the separation line
        column_title = NULL, 
        use_raster=FALSE,
        column_gap = unit(0.25, "mm"))

p
```

```{r}
png("Heatmap_PPFE_merged_all.png", units = "in", width = 14, height = 26, res = 600)
p
dev.off()
```

#===================================

# Save the dataset
```{r}
saveRDS(ppfe ,"ppfe_final_b1_b2_09_10_2024.rds")
ppfe<- readRDS("ppfe_final_b1_b2_09_10_2024.rds")
```

#==================================

# subset the lineages
```{r}
ppfe_epi <- subset(ppfe, Lineage == "Epithelium")
saveRDS(ppfe_epi,  "ppfe_b1_b2_epithelium_09102024.rds")
rm(ppfe_epi)
```

```{r}
ppfe_mes <- subset(ppfe, Lineage == "Stroma")
saveRDS(ppfe_mes,  "ppfe_b1_b2_stroma_09102024.rds")
rm(ppfe_mes)
```

```{r}
ppfe_endo <- subset(ppfe, Lineage == "Endothelium")
saveRDS(ppfe_endo,  "ppfe_b1_b2_endothelium_09102024.rds")
rm(ppfe_endo)
```

```{r}
ppfe_imm <- subset(ppfe, Lineage == "Immune")
saveRDS(ppfe_imm,  "ppfe_b1_b2_immune_09102024.rds")
rm(ppfe_imm)
```



#============================
# Downstream for poster
### Celltype_Coarse
```{r}
PPFE_mes_int_clean <- ppfe
rm(ppfe)

PPFE_mes_int_clean$Celltype_ID_coarse <- PPFE_mes_int_clean$Celltype_ID
```

# 3.  Rename Cluster Identities
```{r}
#Change ident
Idents(PPFE_mes_int_clean) <- "Seuratcorrected_snn_res.0.2"


PPFE_mes_int_clean <- SCP::RenameClusters(PPFE_mes_int_clean, group.by = "Seuratcorrected_snn_res.0.2", name = "Lineage_fine",
                            nameslist = c(
                              "Stroma", # 0
                               "Lymphloid",  #1
                               "Lymphloid", #10
                               "Endothelium", #11
                               "Endothelium", #12 
                               "Myeloid", #13
                               "Epithelium", #14 
                               "Epithelium", #15
                               "Endothelium", #16
                               "Epithelium", #17
                               "Myeloid", #18
                              "Myeloid", # 19
                             "Lymphloid", # 2
                              "Lymphloid", # 20
                              "Epithelium", # 21
                              "Myeloid", #22 
                               "Epithelium", #3
                               "Epithelium", #4
                               "Myeloid", # 5
                               "Endothelium", #6
                               "Lymphloid", # 7
                               "Myeloid", #8
                               "Stroma") #9 
                            )
```

```{r}
CellDimPlot(PPFE_mes_int_clean, group.by = "Lineage_fine", raster = F, label = F, reduction = "umap", palette = "Dark2")
```
```{r}
SCP::palette_scp(palette = "Dark2", n = 5)
```


```{r}
p <- CellDimPlot(PPFE_mes_int_clean, group.by = "Lineage_fine", raster = F, pt.size = 0.05, reduction = "umap", palcolor = c("#1B9E77" ,"#D95F02", "#7570B3" ,"#FED9BE", "#E7298A"), show_stat = F, xlab = "UMAP_1", ylab = "UAMP_2", legend.position = "none", label = T, label_insitu = T, theme_use = "theme_blank", label.size = 3.5)
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank())  # Remove axis ticks


png(filename = "PPFE_ALL_UMAP.png", height = 10, width = 10, units = "in", res = 600)
#pdf("PPFE_MES_UMAP.pdf", height = 7, width = 7)
p
dev.off()
p
```
```{r}
p <- CellDimPlot(subset(PPFE_mes_int_clean, Celltype_ID != "AE_Endo_Dbl" &
                          Celltype_ID != "Immune_Dbl" &
                          Celltype_ID != "Mast_AE_Dbl"),  
                 group.by = "Celltype_ID", raster = F, pt.size = 0.05, reduction = "umap", show_stat = F, xlab = "UMAP_1", 
                 ylab = "UAMP_2", legend.position = "none", label = T, label_insitu = T, theme_use = "theme_blank", label.size = 3.5)
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank())  # Remove axis ticks


png(filename = "PPFE_ALL_UMAP_fine.png", height = 10, width = 10, units = "in", res = 600)
#pdf("PPFE_MES_UMAP.pdf", height = 7, width = 7)
p
dev.off()
p
```

```{r, fig.width=18}
# Proportion / cell number composition per cluster
ggData = data.frame(prop.table(table(PPFE_mes_int_clean$Lineage_fine, PPFE_mes_int_clean$orig.ident), margin = 2))
colnames(ggData) = c("Celltype_ID", "Orig.Ident",  "value")

ggData <- ggData %>%
 mutate(Disease = substr(Orig.Ident, 1,4))

Batch2_Fren_IDs <- c("PPFE_PPFE21", 
 "PPFE_PPFE22", 
 "PPFE_PPFE25", 
 "PPFE_PPFE26", 
 "PPFE_PPFE27", 
 "PPFE_PPFE28", 
 "PPFE_PPFE29", 
 "PPFE_PPFE30", 
 "PPFE_PPFE31", 
 "PPFE_PPFE32", 
 "PPFE_PPFE33", 
 "PPFE_PPFE34", 
 "PPFE_PPFE35", 
 "PPFE_PPFE37", 
 "PPFE_PPFE38", 
 "PPFE_PPFE40", 
 "PPFE_PPFE23", 
 "PPFE_PPFE24", 
 "PPFE_PPFE36", 
 "PPFE_PPFE39")

BAtch1_Han_IDs <- c("PPFE_PPFE001" , "PPFE_PPFE002" ,  "PPFE_PPFE003" ,  "PPFE_PPFE004" ,  "PPFE_PPFE005" , "PPFE_PPFE006"  , "PPFE_PPFE007"  ,   "PPFE_PPFE008",   "PPFE_PPFE009",   "PPFE_PPFE010",   "PPFE_PPFE011",   "PPFE_PPFE012",   "PPFE_PPFE013",   "PPFE_PPFE014",   "PPFE_PPFE015a",  "PPFE_PPFE015b",  "PPFE_PPFE016",   "PPFE_PPFE017",   "PPFE_PPFE018",   "PPFE_PPFE019",   "PPFE_PPFE020", 
                    "PPFE_PPFE40", 
                    "PPFE_PPFE41", 
                    "PPFE_PPFE42",
                    "PPFE_PPFE43",
                    "PPFE_PPFE44")

CTRL_ids <- c("CTRL_GLE822" ,  "CTRL_GLE891"   ,"CTRL_CTRL002",  "CTRL_GLR632"   ,"CTRL_GLR635",   "CTRL_CTRL007",  "CTRL_GLE639"  , "CTRL_GLR609" ,  "CTRL_GLR725"  ,"CTRL_CTR048"  , "CTRL_CTR068" ,  "CTRL_CTR069" ,  "CTRL_CTR070", "CTRL_CTR058", "CTRL_CTR071" , "CTRL_CTR051")



ggData <- ggData %>%
 mutate(Disease = case_when(Orig.Ident %in% Batch2_Fren_IDs ~ "France_PPFE",
                            Orig.Ident %in% BAtch1_Han_IDs ~ "Germany_PPFE",
                            Orig.Ident %in% CTRL_ids ~ "Germany_CTRL")
 )

ggData$Disease <- factor(ggData$Disease, levels = c("Germany_CTRL", "Germany_PPFE", "France_PPFE"))



PPFE_mes_int_clean$Lineage_fine %>% unique() -> Celltypes
levels(Celltypes)

cluster_scp_pal <- SCP::palette_scp(x = c("Lymphloid", "Myeloid" ,"Endothelium",
                                                            "Stroma","Epithelium"), palcolor = c("#D95F02"  ,"#FED9BE", "#7570B3", "#1B9E77" , "#E7298A"))

patient_order <- ggData %>%
  dplyr::filter(Celltype_ID == 'Lymphloid') %>%
  arrange(desc(value)) %>%
  pull(Orig.Ident)

# Convert Patient_ID to a factor with the specific order
ggData$Orig.Ident <- factor(ggData$Orig.Ident, levels = patient_order)


# Calculate median values for each Celltype_ID within each Disease group
medians <- ggData %>%
  dplyr::filter(Disease =="Germany_PPFE") %>%
  group_by(Disease, Celltype_ID) %>%
  summarize(median_value = median(value)) %>%
  ungroup()

# Order Celltype_ID based on median values
ordered_celltypes <- medians %>%
  group_by(Celltype_ID) %>%
  summarize(overall_median = median(median_value)) %>%
  arrange(overall_median) %>%
  pull(Celltype_ID)
ordered_celltypes

# Update the levels of Celltype_ID in ggData
ggData$Celltype_ID <- factor(ggData$Celltype_ID, levels =  c("Lymphloid", "Myeloid" ,"Endothelium",
                                                            "Stroma","Epithelium")
                             )



p <- ggplot(ggData, aes(x = Orig.Ident, y = value, fill = Celltype_ID)) +
  geom_bar(stat = "identity", position = "stack", size = 0.5, color = "black") +
  labs(title = "Stacked Bar Plot of Cell Type Frequencies by Patient",
       x = "Patient ID",
       y = "Frequency (%)") + 
  scale_fill_discrete(cluster_scp_pal) +
  scale_color_discrete(cluster_scp_pal) +
  scale_fill_manual(values = cluster_scp_pal) +
  scale_color_manual(values = cluster_scp_pal) +
  theme_scp() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))+
  facet_wrap(~Disease, scales = "free_x")

p
```

```{r}
png("Freq4_PPFE_all_lineage_coarse_all.png", units = "in", width = 14, height = 8, res = 600)
p
dev.off()
p
```

```{r}
library(ggpubr)
# Convert disease.ident and Celltype to factors
ggData$Disease <- as.factor(ggData$Disease)
ggData$Celltype_ID <- as.factor(ggData$Celltype_ID)

# Calculate the median frequency for each cell type
median_frequencies <- ggData %>%
  group_by(Celltype_ID) %>%
  summarize(median_freq = median(value)) %>%
  arrange(-median_freq)

# Reorder the Celltype factor levels based on median frequency
ggData$Celltype_ID <- factor(ggData$Celltype_ID, levels = median_frequencies$Celltype_ID)

# Plot
p <- ggplot(ggData, aes(x = Celltype_ID, y = value, fill = Disease)) +
  geom_boxplot(outlier.shape = NA) +
  labs(title = "Comparison of Cell Type Frequencies Between Disease Groups",
       x = "Cell Type",
       y = "Frequency (%)") +
  scale_fill_manual(values = c("royalblue", "red3", "pink")) +
  scale_color_manual(values = c("royalblue", "red3", "pink")) +
  theme_scp() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Add statistical comparisons
p <- p + stat_compare_means(aes(group = Disease), method = "t.test", label = "p.signif")

#==============================================

# Plot
p <- ggplot(ggData, aes(x = Celltype_ID, y = value, fill = Disease)) +
  geom_boxplot(outlier.shape = NA) +
  labs(title = "Comparison of Cell Type Frequencies Between Disease Groups",
       x = "Cell Type",
       y = "Frequency (%)") +
  scale_fill_manual(values = c("royalblue", "red3", "pink")) +
  scale_color_manual(values = c("royalblue", "red3", "pink")) +
  theme_scp() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Add statistical comparisons
p <- p + stat_compare_means(aes(group = Disease), label = "p.signif")

# Display the plot
print(p)
```
```{r}
png("Freq3_PPFE_all_lineage_coarse_all.png", units = "in", width = 9, height = 8, res = 600)
p
dev.off()
p
```

```{r}
# Reorder the Celltype factor levels based on median frequency
PPFE_mes_int_clean$Celltype_ID_coarse <- factor(PPFE_mes_int_clean$Celltype_ID_coarse, levels = c("Alveolar_Fb", "Pericytes" ,"Smooth_Muscle",
                                                            "Subpleural_Fb","Mesothelium", 
                                                            "Peribronchial_Fb", "MyoFb","Adventitial_Fb")
                                                )

CellStatPlot(PPFE_mes_int_clean, stat.by = "disease.ident", group.by = "Celltype_ID_coarse", stat_type = "count", plot_type = "bar", palcolor = c("royalblue", "red3"))
```
```{r}
p <- CellDimPlot(PPFE_mes_int_clean, group.by = "Celltype_ID_coarse", raster = F, pt.size = 0.15, reduction = "ReUMAP_011", palette = "Paired", show_stat = F, xlab = "UMAP_1", ylab = "UAMP_2", legend.position = "none")+
  theme(axis.text = element_blank(),   # Remove axis text
        axis.ticks = element_blank())  # Remove axis ticks


png(filename = "PPFE_MES_UMAP.png", height = 7, width = 7, units = "in", res = 600)
#pdf("PPFE_MES_UMAP.pdf", height = 7, width = 7)
p
dev.off()
p
```
```{r}
SCP::palette_scp(palette = "Set1", n = length(PPFE_mes_int_clean$orig.ident %>% unique()), matched = F) -> palette

p <- DimPlot(PPFE_mes_int_clean, group.by = c("orig.ident"),shuffle = T, raster = F, label = F, combine = T, reduction = "ReUMAP_11")+
  theme_scp()+NoLegend()+ggtitle("Subject")+
  scale_color_manual(values = as.vector(palette))|
  DimPlot(PPFE_mes_int_clean, group.by = c("disease.ident"),shuffle = T, raster = F, label = F, combine = T, reduction = "ReUMAP_11", cols = c("royalblue", "red3"))+
  theme_scp()+NoLegend()+ggtitle("Disease")

png(filename = "PPFE_Mesenchyme_subject_Disease_UMAP.png", height = 7, width = 7, units = "in", res = 600)
#pdf(file = "PPFE_Mesenchyme_subject_Disease_UMAP.pdf", width = 14, height = 7)
p
dev.off()
p
```

```{r, fig.width=4, fig.height=6}
PPFE_mes_int_clean$cohort_disease <- paste0(PPFE_mes_int_clean$Cohort, "_", PPFE_mes_int_clean$disease.ident)
PPFE_mes_int_clean$cohort_disease <- factor(PPFE_mes_int_clean$cohort_disease, levels = c("Germany_CTRL", "France_PPFE", "Germany_PPFE"))
p <- CellStatPlot(PPFE_mes_int_clean, stat.by = "Lineage_fine", group.by = "cohort_disease", plot_type = "trend", palcolor = c("#1B9E77" ,"#D95F02", "#7570B3","#FED9BE", "#E7298A"))

p

png("Stat_plot_by_Lineage_fine.png", units = "in", height = 6, width = 4, res = 300)
p
dev.off()
```

